### ISSUE TITLE
Could you provide the model for Segmentation challenge from ShapeNet Core55

### ISSUE THREAD

**Issue by zjhthu** [facebookresearch/SparseConvNet#10]
First, Thanks for the great work!
Could you provide the model or code your group used in Segmentation from ShapeNet Core55
, which is described in this paper:<https://arxiv.org/pdf/1710.06104.pdf>.
Thank you very much

**Comment by btgraham** [comment]
Please see 
https://github.com/facebookresearch/SparseConvNet/blob/master/PyTorch/sparseconvnet/networkArchitectures.py#L209
Thanks for your interest.

**Comment by zjhthu** [comment]
thanks very much!
