### ISSUE TITLE
About using tensorboardX to visualize the network structure

### ISSUE THREAD

**Issue by fruityangyang** [facebookresearch/SparseConvNet#100]
Thank you for sharing your amazing code! Now, i'm trying to use tensorboardX to visualize the network structure, but it failed. Can tensorboardX be used to visualize the sparseconvnet? If don't, which tool do  you recommend to visualize the network structure?

**Comment by btgraham** [comment]
scn.Sequential inherits from torch.nn.Sequential so standard methods might work.
I have not really looked into this yet, I am afraid.
Ben
