### ISSUE TITLE
about training speed of Scannet example

### ISSUE THREAD

**Issue by mzy97** [facebookresearch/SparseConvNet#101]
thank you for the great work, but i have a question when training /examples/Scannet/unet.py.

my environment:
ubuntu 16.04
pytorch 1.0.1
GPU titanx(pascal) 12GB memory
memory 20G

parameter settings:
`# Options
m = 32 # 16 or 32
residual_blocks=True #True or False
block_reps = 2 #Conv block repetition factor: 1 or 2
scale=50  #Voxel size = 1/scale
val_reps=1 # Number of test views, 1 or more
batch_size=6`

it is normal to train 1 epoch in 47min?
thank you

**Comment by btgraham** [comment]
Please see: https://github.com/facebookresearch/SparseConvNet/issues/78
The limiting factor is probably (?) pre-processing the 3D points clouds on the CPU.

**Comment by mzy97** [comment]
> Please see: #78
> The limiting factor is probably (?) pre-processing the 3D points clouds on the CPU.

I found that using more CPU will increase the speed. I wonder what number of CPU are you using when training
