### ISSUE TITLE
Submanifold Conv Extremely Slow 

### ISSUE THREAD

**Issue by poodarchu** [facebookresearch/SparseConvNet#103]
I build a network like this:
`self.middle_conv = scn.Sequential(
113             scn.SubmanifoldConvolution(3, num_input_features, 16, 3, False),
114             scn.BatchNormReLU(16),
115             scn.SubmanifoldConvolution(3, 16, 16, 3, False),
116             scn.BatchNormReLU(16), scn.Convolution(3, 16, 32, 3, 2, False),
117             scn.BatchNormReLU(32),
118             scn.SubmanifoldConvolution(3, 32, 32, 3, False),
119             scn.BatchNormReLU(32),
120             scn.SubmanifoldConvolution(3, 32, 32, 3, False),
121             scn.BatchNormReLU(32), scn.Convolution(3, 32, 64, 3, 2, False),
122             scn.BatchNormReLU(64),
123             scn.SubmanifoldConvolution(3, 64, 64, 3, False),
124             scn.BatchNormReLU(64),
125             scn.SubmanifoldConvolution(3, 64, 64, 3, False),
126             scn.BatchNormReLU(64),
127             scn.SubmanifoldConvolution(3, 64, 64, 3, False),
128             scn.BatchNormReLU(64), scn.Convolution(3, 64, 64, 3, 2, False),
129             scn.BatchNormReLU(64),
130             scn.SubmanifoldConvolution(3, 64, 64, 3, False),
131             scn.BatchNormReLU(64),
132             scn.SubmanifoldConvolution(3, 64, 64, 3, False),
133             scn.BatchNormReLU(64),
134             scn.SubmanifoldConvolution(3, 64, 64, 3, False),
135             scn.BatchNormReLU(64),
136             scn.Convolution(3, 64, 64, (3, 1, 1), (2, 1, 1), False),
137             scn.BatchNormReLU(64), scn.SparseToDense(3, 64))`

it turns out that subm is exteremly slow.

how to solve this?

**Comment by poodarchu** [comment]
submainfoldConvolution.py: line 66

**Comment by panyunyi97** [comment]
buy a V100,u will find it extremely fast.
