### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by nbrodic88** [facebookresearch/SparseConvNet#108]
Do you have any recommendations for running your script on Windows 10 OS?

**Comment by btgraham** [comment]
I haven't tested it on anything but Linux, I am afraid. 
It might work, possibly with some changes to setup.py to make sure the paths are pointing to the right places.

**Comment by nbrodic88** [comment]
Thank you

**Comment by dengyuhk** [comment]
@nbrodic88，have you solve the problem on Win 10 OS?

**Comment by nbrodic88** [comment]
Hi,
nope, I have continued with Ubuntu

**Comment by dengyuhk** [comment]
@nbrodic88, Well, maybe I will switch to Ubuntu later.
 Thanks for your answer.
