### ISSUE TITLE
torch version example problem

### ISSUE THREAD

**Issue by zjhthu** [facebookresearch/SparseConvNet#11]
I am trying the torch version examples, `th hello.lua`, but get `SparseToDense.lua:39: bad argument #1 to 'size' (torch.CudaTensor expected, got boolean)`, the pytorch version is OK. 
I remember that I have successfully running the torch version examples, so I think this error may be caused by some updates of torch or others, then I tried several versions of torch, but this  error still happens.

**Comment by zjhthu** [comment]
I am using Ubuntu 16.04, latest [torch](http://torch.ch/docs/getting-started.html),

**Comment by btgraham** [comment]
Sorry for the delay. Now fixed.
