### ISSUE TITLE
scannet data aug question

### ISSUE THREAD

**Issue by chenkl1995** [facebookresearch/SparseConvNet#112]
I am not really know what the following code means, could you give some explains about it.
` m[0][0]*=np.random.randint(0,2)*2-1`
which from [https://github.com/facebookresearch/SparseConvNet/blob/master/examples/ScanNet/data.py#L59](https://github.com/facebookresearch/SparseConvNet/blob/master/examples/ScanNet/data.py#L59)

Thanks!

**Comment by btgraham** [comment]
M is a 3x3 matrix for doing affine-transform data augmentation.
That line makes it do mirror-flips with probability 50%.
