### ISSUE TITLE
Need to train without the features.

### ISSUE THREAD

**Issue by aniqueakhtar** [facebookresearch/SparseConvNet#115]
Hello,
I have a 3D point cloud data without any features. I want to do 3D segmentation on it. If I leave the `features` part of the sparse tensor, it gives an error. If I give features as `zeros` it doesn't learn anything.
Any advice on how I can train the network when I have no features?
Thanks.

**Comment by btgraham** [comment]
A vector of ones with shape (n_points,1) should work.
