### ISSUE TITLE
empty active coordinate input

### ISSUE THREAD

**Issue by EvanDSchwab** [facebookresearch/SparseConvNet#119]
Hello,

Is there a default way to input an image with no active coordinates to the sparse CNN? Currently I am artificially inputting a single active coordinate with a feature value of 0? But I am afraid this may raise some unintended consequences.

Thanks
EDS

**Comment by btgraham** [comment]
I don't think any good can come from this, but
```
import torch, sparseconvnet as scn
m=scn.InputLayer(3,64)
batch_size=1
empty_input=(torch.LongTensor(0,3),torch.FloatTensor(0,3),batch_size)
m(empty_input)
```
gives
`SparseConvNetTensor<<features=tensor([], size=(0, 3)),features.shape=torch.Size([0, 3]),batch_locations=tensor([], size=(0, 4), dtype=torch.int64),batch_locations.shape=torch.Size([0, 4]),spatial size=tensor([64, 64, 64])>>`
