### ISSUE TITLE
why is output size same as input size?

### ISSUE THREAD

**Issue by etienne87** [facebookresearch/SparseConvNet#12]
I am running the hello world, I do not understand why inputing a spatial size of 10x10 leads to an output spatial size of 10x10. Shouldn't the downsizing reduce those?

**Comment by btgraham** [comment]
Yes. In the example 10x10 is the output size and the input size is something bigger. The line
"inputSpatialSize = model.input_spatial_size(torch.LongTensor([10, 10]))"
does the calculation of how big exactly should the input spatial size be in order to get an output with spatial size 10x10.

**Comment by etienne87** [comment]
Ah! Thanks a lot, that makes sense. So if i have sparse image of size (W,H) and use 3 maxpoolings with stride=2 I must use: "inputSpatialSize = model.input_spatial_size(torch.LongTensor([H>>3, W>>3])"

**Comment by dongxiao92** [comment]
So the parameter passed to 'input_spatial_size' should be the desired output spatial size, right?
