### ISSUE TITLE
Reuse rulebooks for second network

### ISSUE THREAD

**Issue by maxjaritz** [facebookresearch/SparseConvNet#123]
Hi,
I would like to use SparseConvNet in adversarial learning. Thus, the generator and discriminator operate on the same locations, but on different features. Is it possible to save computation by reusing the rulebooks and meta data from the generator in the discriminator?

Thanks

**Comment by btgraham** [comment]
Given a SparseConvNetTensors (produced by an InputLayer object for example), you can create a new SparseConvNetTensor reusing the metadata and spatial_size tensor, but with a different features tensor that has the same number of rows.

However, what do you mean by a 'generator' in the context of SparseConvNet? Some layers (FullConvolution, Sparsify) produce output with a different metadata object to input, so the above will not work.

**Comment by maxjaritz** [comment]
In my case, the generator is a UNet for 3D Segmentation. The discriminator could have the same architecture. It takes the generator's output as input and predicts fake or real for each point in the point cloud.

I see, so only the metadata from the SparseConvNetTensor can be reused. After a FullConvolution or Sparsify layers the metadata is different due to different activations.
