### ISSUE TITLE
The metric of IOU

### ISSUE THREAD

**Issue by jzhzhang** [facebookresearch/SparseConvNet#126]
I'm looking for the method of Iou computation for the ScanNet. But I find it's a little different between yours and the dataset provider.

[offical evaluation scripts for the 3D semantic label](https://github.com/ScanNet/ScanNet/blob/master/BenchmarkScripts/3d_evaluation/evaluate_semantic_label.py )
[yours](https://github.com/facebookresearch/SparseConvNet/blob/master/examples/ScanNet/iou.py)
It seems like you didn't count the number of vertexes which are predicted in another 20 class labels. 
For example, the pred label is 25(not in the valid label) and gt label is 1(in the valid number), your method seems would ignore this vertex, which could lead to a higher IOU result.
I am not sure that I have fully understood it. Do you have any comments?
Thanx!

**Comment by btgraham** [comment]
My example UNet only predicts valid labels, so I think my evaluation code is OK.
There might be an advantage to letting network predict classes that appear in the training data but are not one of the 20 valid classes. I have not tried that yet.
