### ISSUE TITLE
The OutputLayer raise `RuntimeError: CUDA error: an illegal memory access was encountered`

### ISSUE THREAD

**Issue by chenyuntc** [facebookresearch/SparseConvNet#127]
I downsample the input points to 8x, and apply the `OutputLayer`, it return tensor with the correct size, but when I try to see the tensor value, it raise `RuntimeError: CUDA error: an illegal memory access was encountered`

**Comment by chenyuntc** [comment]
Besides, when I try use a CPU version, it raise

**Comment by btgraham** [comment]
OutputLayer can only be used as a pair with InputLayer, i.e. for UNets where the input spatial size matches the output spatial size.
If you downscale by a factor or 8x, you can access the features and locations using
tensor.features and tensor.get_spatial_locations().
