### ISSUE TITLE
Is it possible to access the batch size of a sparse tensor?

### ISSUE THREAD

**Issue by LeonhardFeiner** [facebookresearch/SparseConvNet#131]
Thank you for your framework :)

 The `InputLayer` enables totally empty batches:
> batch_size if given, set a lower bound on the the number of samples in the output tensor.
>     Batch size can normally be inferred from the last column of coords, but this may fail if
>     some of the batch items are totally empty

Unfortunatelly, following snippet only works if there are no totally empty items within each batch:
```
def get_batch_size(sparse_tensor):
    return sparse_tensor.get_spatial_locations()[:,-1].max() + 1
```
Is there any better and more general solution than this one?

**Comment by btgraham** [comment]
I have added 'tensor.batch_size()'.
