### ISSUE TITLE
fp16 gradient overflow

### ISSUE THREAD

**Issue by panyunyi97** [facebookresearch/SparseConvNet#133]
we use apex for scn,but found that it's easy to fall into gradient overflow,but without this issue when using fp32.in addition,scn cannot really use the gpu efficiently,when u run it on v100,the pwr usage/cap keep below 80w/300w.

**Comment by Jaehyun0818** [comment]
Hello, panyunyi97. I'm trying to use apex for scn these days.
However, There is an error like "RuntimeError: expected scalar type Float but found Half"
So, I wonder that scn supports fp16.
Thank you!!

**Comment by panyunyi97** [comment]
> Hello, panyunyi97. I'm trying to use apex for scn these days.
> However, There is an error like "RuntimeError: expected scalar type Float but found Half"
> So, I wonder that scn supports fp16.
> Thank you!!

Several month ago, I found it works when i using apex, but I really forget the details about it (cause i didn't using fp16 in my experiment), the only thing that i could tell u is the method is feasible. Just follow the guidance of the official docs and do it step by step.
