### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by HermanZYZ** [facebookresearch/SparseConvNet#136]
Hi，I am new about pytorch. Now, I want to install this repo, but meet the following error whem run `develop.sh`:

> Input SparseConvNetTensor: Traceback (most recent call last):
  File "examples/hello-world.py", line 62, in <module>
    print('Input SparseConvNetTensor:', input)
  File "/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/sparseConvNetTensor.py", line 62, in __repr__
    ',spatial size=' + repr(self.spatial_size) + \
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/tensor.py", line 114, in __repr__
    return torch._tensor_str._str(self)
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 311, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 209, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 87, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/functional.py", line 227, in isfinite
    return (tensor == tensor) & (tensor.abs() != inf)
RuntimeError: CUDA error: invalid device function

I use conda to install pytorch 1.3.0 and cudatoolkit 10.0. And when I run the command `nvcc --version`, it shows that :

> nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

I don't know how to fix. I am from the [issue](https://github.com/facebookresearch/SparseConvNet/issues/132#issue-512610704).

**Comment by HermanZYZ** [comment]
The following is the logs when running `develop.sh`:

> running develop                                                                                                                         
running egg_info                                                                                                                        
creating sparseconvnet.egg-info                                                                                                         
writing sparseconvnet.egg-info/PKG-INFO                                                                                                 
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt                                                                 
writing top-level names to sparseconvnet.egg-info/top_level.txt                                                                         
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'                                                                              
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)                                                     
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'                                                                              
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'                                                                              
running build_ext                                                                                                                       
building 'sparseconvnet.SCN' extension                                                                                                  
creating build                                                                                                                          
creating build/temp.linux-x86_64-3.6                                                                                                    
creating build/temp.linux-x86_64-3.6/sparseconvnet                                                                                      
creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN                                                                                  
/usr/local/cuda-10.0/bin/nvcc -I/home/zhuyzh9/.conda/envs/pillars/include -I/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/SCN/ -I/home
/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/t
orch/include/torch/csrc/api/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/TH -I/home/zhuyzh9/.co
nda/envs/pillars/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/zhuyzh9/.conda/envs/pillars/includ
e/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_
NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -
DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=sm_70                
/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion r$
sulted in a change of sign                                                                                                              
                                                                                                                                        
/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion r$
sulted in a change of sign
gcc -pthread -B /home/zhuyzh9/.conda/envs/pillars/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-
prototypes -fPIC -I/home/zhuyzh9/.conda/envs/pillars/include -I/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/SCN/ -I/home/zhuyzh9/.con
da/envs/pillars/lib/python3.6/site-packages/torch/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/
torch/csrc/api/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/TH -I/home/zhuyzh9/.conda/envs/pill
ars/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/zhuyzh9/.conda/envs/pillars/include/python3.6m
-c sparseconvnet/SCN/sparseconvnet_cuda.cpp -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/sparseconvnet_cuda.o -std=c++11 -fopenmp -D
TORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/zhuyzh9/.conda/envs/pillars/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-
prototypes -fPIC -I/home/zhuyzh9/.conda/envs/pillars/include -I/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/SCN/ -I/home/zhuyzh9/.con
da/envs/pillars/lib/python3.6/site-packages/torch/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/
torch/csrc/api/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/TH -I/home/zhuyzh9/.conda/envs/pill
ars/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/zhuyzh9/.conda/envs/pillars/include/python3.6m
-c sparseconvnet/SCN/pybind.cpp -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/pybind.o -std=c++11 -fopenmp -DTORCH_API_INCLUDE_EXTENS
ION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/sparseconvnet
g++ -pthread -shared -B /home/zhuyzh9/.conda/envs/pillars/compiler_compat -L/home/zhuyzh9/.conda/envs/pillars/lib -Wl,-rpath=/home/zhuyz
h9/.conda/envs/pillars/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o build/temp.linux-x86_
64-3.6/sparseconvnet/SCN/sparseconvnet_cuda.o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/pybind.o -L/usr/local/cuda-10.0/lib64 -lcuda
rt -o build/lib.linux-x86_64-3.6/sparseconvnet/SCN.cpython-36m-x86_64-linux-gnu.so
/home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5" is unsafe for cross
-compilation
/home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linu
x-gnu" is unsafe for cross-compilation
/home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib" is
unsafe for cross-compilation
/home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/lib/x86_64-linux-gnu" is unsafe for cross-compilati
on
/home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/lib/../lib" is unsafe for cross-compilation
/home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/x86_64-linux-gnu" is unsafe for cross-compi
lation
/home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/../lib" is unsafe for cross-compilation
/home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../.." is unsafe
for cross-compilation
copying build/lib.linux-x86_64-3.6/sparseconvnet/SCN.cpython-36m-x86_64-linux-gnu.so -> sparseconvnet
Creating /home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/sparseconvnet.egg-link (link to .)
Removing sparseconvnet 0.2 from easy-install.pth file
sparseconvnet 0.2 is already the active version in easy-install.pth

Installed /data/zhuyzh9/Tools/SparseConvNet
Processing dependencies for sparseconvnet==0.2
Finished processing dependencies for sparseconvnet==0.2
Using CUDA.
Input SparseConvNetTensor: Traceback (most recent call last):
  File "examples/hello-world.py", line 62, in <module>
    print('Input SparseConvNetTensor:', input)
  File "/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/sparseConvNetTensor.py", line 62, in __repr__
    ',spatial size=' + repr(self.spatial_size) + \
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/tensor.py", line 114, in __repr__
    return torch._tensor_str._str(self)
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 311, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 209, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 87, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
  File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/functional.py", line 227, in isfinite
    return (tensor == tensor) & (tensor.abs() != inf)
RuntimeError: CUDA error: invalid device function

**Comment by dropletpeace** [comment]
Hello

> The following is the logs when running `develop.sh`:
> 
> > running develop
> > running egg_info
> > creating sparseconvnet.egg-info
> > writing sparseconvnet.egg-info/PKG-INFO
> > writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
> > writing top-level names to sparseconvnet.egg-info/top_level.txt
> > writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> > package init file 'sparseconvnet/SCN/**init**.py' not found (or not a regular file)
> > reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> > writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> > running build_ext
> > building 'sparseconvnet.SCN' extension
> > creating build
> > creating build/temp.linux-x86_64-3.6
> > creating build/temp.linux-x86_64-3.6/sparseconvnet
> > creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN
> > /usr/local/cuda-10.0/bin/nvcc -I/home/zhuyzh9/.conda/envs/pillars/include -I/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/SCN/ -I/home
> > /zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/t
> > orch/include/torch/csrc/api/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/TH -I/home/zhuyzh9/.co
> > nda/envs/pillars/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/zhuyzh9/.conda/envs/pillars/includ
> > e/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_
> > NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -
> > DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=sm_70
> > /home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion r$
> > sulted in a change of sign
> > /home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion r$
> > sulted in a change of sign
> > gcc -pthread -B /home/zhuyzh9/.conda/envs/pillars/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-
> > prototypes -fPIC -I/home/zhuyzh9/.conda/envs/pillars/include -I/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/SCN/ -I/home/zhuyzh9/.con
> > da/envs/pillars/lib/python3.6/site-packages/torch/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/
> > torch/csrc/api/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/TH -I/home/zhuyzh9/.conda/envs/pill
> > ars/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/zhuyzh9/.conda/envs/pillars/include/python3.6m
> > -c sparseconvnet/SCN/sparseconvnet_cuda.cpp -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/sparseconvnet_cuda.o -std=c++11 -fopenmp -D
> > TORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
> > cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> > gcc -pthread -B /home/zhuyzh9/.conda/envs/pillars/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-
> > prototypes -fPIC -I/home/zhuyzh9/.conda/envs/pillars/include -I/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/SCN/ -I/home/zhuyzh9/.con
> > da/envs/pillars/lib/python3.6/site-packages/torch/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/
> > torch/csrc/api/include -I/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/include/TH -I/home/zhuyzh9/.conda/envs/pill
> > ars/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/home/zhuyzh9/.conda/envs/pillars/include/python3.6m
> > -c sparseconvnet/SCN/pybind.cpp -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/pybind.o -std=c++11 -fopenmp -DTORCH_API_INCLUDE_EXTENS
> > ION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
> > cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> > creating build/lib.linux-x86_64-3.6
> > creating build/lib.linux-x86_64-3.6/sparseconvnet
> > g++ -pthread -shared -B /home/zhuyzh9/.conda/envs/pillars/compiler_compat -L/home/zhuyzh9/.conda/envs/pillars/lib -Wl,-rpath=/home/zhuyz
> > h9/.conda/envs/pillars/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o build/temp.linux-x86_
> > 64-3.6/sparseconvnet/SCN/sparseconvnet_cuda.o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/pybind.o -L/usr/local/cuda-10.0/lib64 -lcuda
> > rt -o build/lib.linux-x86_64-3.6/sparseconvnet/SCN.cpython-36m-x86_64-linux-gnu.so
> > /home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5" is unsafe for cross
> > -compilation
> > /home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linu
> > x-gnu" is unsafe for cross-compilation
> > /home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib" is
> > unsafe for cross-compilation
> > /home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/lib/x86_64-linux-gnu" is unsafe for cross-compilati
> > on
> > /home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/lib/../lib" is unsafe for cross-compilation
> > /home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/x86_64-linux-gnu" is unsafe for cross-compi
> > lation
> > /home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/../lib" is unsafe for cross-compilation
> > /home/zhuyzh9/.conda/envs/pillars/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../.." is unsafe
> > for cross-compilation
> > copying build/lib.linux-x86_64-3.6/sparseconvnet/SCN.cpython-36m-x86_64-linux-gnu.so -> sparseconvnet
> > Creating /home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/sparseconvnet.egg-link (link to .)
> > Removing sparseconvnet 0.2 from easy-install.pth file
> > sparseconvnet 0.2 is already the active version in easy-install.pth
> > Installed /data/zhuyzh9/Tools/SparseConvNet
> > Processing dependencies for sparseconvnet==0.2
> > Finished processing dependencies for sparseconvnet==0.2
> > Using CUDA.
> > Input SparseConvNetTensor: Traceback (most recent call last):
> > File "examples/hello-world.py", line 62, in 
> > print('Input SparseConvNetTensor:', input)
> > File "/data/zhuyzh9/Tools/SparseConvNet/sparseconvnet/sparseConvNetTensor.py", line 62, in **repr**
> > ',spatial size=' + repr(self.spatial_size) + 
> >   File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/tensor.py", line 114, in **repr**
> > return torch._tensor_str._str(self)
> > File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 311, in _str
> > tensor_str = _tensor_str(self, indent)
> > File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 209, in _tensor_str
> > formatter = _Formatter(get_summarized_data(self) if summarize else self)
> > File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/_tensor_str.py", line 87, in **init**
> > nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
> > File "/home/zhuyzh9/.conda/envs/pillars/lib/python3.6/site-packages/torch/functional.py", line 227, in isfinite
> > return (tensor == tensor) & (tensor.abs() != inf)
> > RuntimeError: CUDA error: invalid device function

Hello HermanZYZ, I met the same problem like you, have you fixed yet?
Hope for your reply, thank you!

**Comment by btgraham** [comment]
I think this might have been caused with a particular version of PyTorch. I think it should work with the latest version.
Ben
