### ISSUE TITLE
When I  run'bash build.sh' or 'bash develop.sh' in NVIDIA Xavier,  I would get the same issue. how to solve it? thanks!

### ISSUE THREAD

**Issue by shaoquanfeng** [facebookresearch/SparseConvNet#137]
sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: type name is not allowed

sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: expected an expression

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: type name is not allowed

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: expected an expression

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: type name is not allowed

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: expected an expression

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: type name is not allowed

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: expected an expression

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: type name is not allowed

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: expected an expression

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: type name is not allowed

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: expected an expression

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: type name is not allowed

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: expected an expression

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: type name is not allowed

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: expected an expression

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: type name is not allowed

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: expected an expression

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: type name is not allowed

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: expected an expression

54 errors detected in the compilation of "/tmp/tmpxft_00003903_00000000-6_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
Traceback (most recent call last):
  File "examples/hello-world.py", line 8, in <module>
    import sparseconvnet as scn
ModuleNotFoundError: No module named 'sparseconvnet'

**Comment by Codeczh** [comment]
It seems that you haven't installed the sparseconvnet, you can try `python setup.py install` and `python examples/hello-world.py`

**Comment by btgraham** [comment]
Please check you have the most recent version of PyTorch installed before installing SparseConvNet.
