### ISSUE TITLE
how to subtract 2 sparse tensors?

### ISSUE THREAD

**Issue by etienne87** [facebookresearch/SparseConvNet#14]
Is there a workaround to substract 2 sparse tensors ? (representing same spatial size)

**Comment by btgraham** [comment]
Are you looking for somthing like AddTable (https://github.com/facebookresearch/SparseConvNet/blob/master/PyTorch/sparseconvnet/tables.py#L22) but for Subtraction?

import sparseconvnet as scn
import torch
class SubtractTable(torch.nn.Module):
    def forward(self, input):
        output = scn.SparseConvNetTensor()
        output.metadata = input[0].metadata
        output.spatial_size = input[0].spatial_size
        output.features=input[0].features-input[1].features
        return output
    def input_spatial_size(self,out_size):
        return out_size

**Comment by etienne87** [comment]
Thanks a lot! They do substract at same spatial locations, right?

**Comment by etienne87** [comment]
So I am trying like this: 
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 13 15:25:45 2017
"""
import torch
import sparseconvnet as scn

class SubtractTable(torch.nn.Module):
    def forward(self, input):
        output = scn.SparseConvNetTensor()
        output.metadata = input[0].metadata
        output.spatial_size = input[0].spatial_size
        output.features=input[0].features-input[1].features
        return output
    def input_spatial_size(self,out_size):
        return out_size
differ = SubtractTable()
dummyModel = scn.Sequential()
dummyModel.add(SubtractTable)
inputSpatialSize = torch.LongTensor([100, 100])
msg1 = [
    " X   X  XXX  X    X    XX                                       ",
    " X   X  X    X    X   X  X                                      ",
    " XXXXX  XX   X    X   X  X                                      ",
    " X   X  X    X    X   X  X                                      ",
    " X   X  XXX  XXX  XXX  XX                                       "]

msg2 = [
    " X   X  XXX  X    X    XX     X       X   XX   XXX   X    XXX   ",
    " X   X  X    X    X   X  X    X       X  X  X  X  X  X    X  X  ",
    " XXXXX  XX   X    X   X  X    X   X   X  X  X  XXX   X    X   X ",
    " X   X  X    X    X   X  X     X X X X   X  X  X  X  X    X  X  ",
    " X   X  XXX  XXX  XXX  XX       X   X     XX   X  X  XXX  XXX   "]

#Round 1
first_input = scn.InputBatch(2, inputSpatialSize)
first_input.addSample()
for y, line in enumerate(msg1):
    for x, c in enumerate(line):
        if c == 'X':
            location = torch.LongTensor([x, y])
            featureVector = torch.FloatTensor([1])
            first_input.setLocation(location, featureVector, 0)
#Round 2
second_input = scn.InputBatch(2, inputSpatialSize)
second_input.addSample()
for y, line in enumerate(msg2):
    for x, c in enumerate(line):
        if c == 'X':
            location = torch.LongTensor([x, y])
            featureVector = torch.FloatTensor([1])
            second_input.setLocation(location, featureVector, 0)
print(first_input.getSpatialLocations().size(), second_input.getSpatialLocations().size() )            
diff = differ((second_input,first_input))
diff = scn.SparseToDense(diff)
```
I get following message:

> ((47L, 3L), (101L, 3L))
Traceback (most recent call last):
  File "substract.py", line 74, in <module>
    diff = adder((second_input,first_input))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/itsame/workspace/SparseConvNet/PyTorch/sparseconvnet/tables.py", line 27, in forward
    output.features=sum([i.features for i in input])
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 293, in __add__
    return self.add(other)
RuntimeError: inconsistent tensor size, expected r_ [101 x 1], t [101 x 1] and src [47 x 1] to have the same number of elements, but got 101, 101 and 47 elements respectively at /pytorch/torch/lib/TH/generic/THTensorMath.c:887

What I would like is to perform sparse spatial substraction between 2 different feature maps of same spatial size n,c,h,w. The substractions should occur only at specified locations. Everywhere else it must either do nothing or output second_input elements.

**Comment by btgraham** [comment]
At the moment, only merging layers with the same sparsity pattern is supported (i.e. for making ResNet style blocks). Other types of merges could be implemented.

What the use case? Preparing input to a ConvNet. Or an operation taking place inside the ConvNet?

**Comment by etienne87** [comment]
I was hoping to implement sparse recurrent convolutions

**Comment by etienne87** [comment]
Current Workaround in pure python :
```
class SubstractSparseDense(torch.nn.Module):
    def forward(self, input):
        #a sparse
        #b dense
        a,b = input
        output = scn.SparseConvNetTensor()
        output.metadata = a.metadata
        output.spatial_size = a.spatial_size
        axy = a.getSpatialLocations()[:,:2]
        y = axy[:,0]
        x = axy[:,1]
        output.features = a.features - b.data[:,:,y,x]
        return output
           
    def input_spatial_size(self,out_size):
        return out_size

first_input_dense = densifier(first_input)
output2 = differ((second_input,first_input_dense))
dense_output2 = densifier(output2).data.numpy()[0,0]
diff = dense_output - dense_output2

print(diff.shape[0],diff.shape[1])

for y in range(diff.shape[0]):
    for x in range(diff.shape[1]):
        d = diff[y,x]
        if d >= 1:
            print('X', end='')
        else:
            print(' ', end='')
    print('\n')
```    
outputs: 

>                            X       X   XX   XXX   X    XXX    
>                            X       X  X  X  X  X  X    X  X   
>                            X   X   X  X  X  XXX   X    X   X  
>                             X X X X   X  X  X  X  X    X  X   
>                               X   X     XX   X  X  XXX  XXX

**Comment by btgraham** [comment]
Could you please tell me a bit more about your application. What is the input data? How is it labelled? Or you can e-mail me at btgraham@gmail.com.
Ben
