### ISSUE TITLE
NetworkInNetwork help

### ISSUE THREAD

**Issue by dtczhl** [facebookresearch/SparseConvNet#141]
Hi, 
I am trying to understand your codes. There is a layer called NetworkInNetwork, which I don't understand (I'm a beginner for machine learning). Could you explain to me what is NetworkInNetwork and how you implement it? 
Thank you for your help.

**Comment by btgraham** [comment]
It is a 1x1 Convolution (c.f. https://arxiv.org/abs/1312.4400). 
For Sparse ConvNets it is a special case as the sparsity pattern does not change. It is just a matrix multplication.

I would recommend using one of the networks defined in networkArchitectures as a starting point, i.e.
https://github.com/facebookresearch/SparseConvNet/blob/master/sparseconvnet/networkArchitectures.py#L203

**Comment by dtczhl** [comment]
@btgraham Thanks for your quick reply. It helps a lot.
