### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by dtczhl** [facebookresearch/SparseConvNet#142]
Hi, 

I am wondering if anyone successfully converts the model and run it on Android? I use the [Pytorch Mobile framework](https://pytorch.org/mobile/home/), but it occurs errors
```
RuntimeError: 
Unknown builtin op: aten::getSpatialLocations.
Could not find any similar ops to aten::getSpatialLocations. This op may not exist or may not be currently supported in TorchScript.
```

Any suggestions would be greatly appreciated.

**Comment by btgraham** [comment]
Sorry, it is not implemented yet.
