### ISSUE TITLE
Question about strided convolution

### ISSUE THREAD

**Issue by XuyangBai** [facebookresearch/SparseConvNet#143]
Hi, Thank you so much for your sharing. I have a question regards the strided convolution. In your paper you mentioned that "An SC convolution computes the set of active sites in the same way as a regular convolution: it looks for the presence of any active sites in its receptive field of size f^d." Does it means that if using for 3D point cloud, you first need to voxelize the point cloud(specify a voxel size) and then find the active sites in the next layer to apply this sparse convolution technique ? If so, for the pooling operation, do you need to double the voxel size in the previous layer?

Thanks a lot.

**Comment by btgraham** [comment]
If you are doing 3D segmentation with a UNet, you voxelize the point cloud once to form the input (see https://github.com/facebookresearch/SparseConvNet/blob/master/examples/ScanNet/data.py). Pooling operations implicitly double the size of the voxels, but the upsampling on the other size of the UNet cancels this out so you get one output prediction for each active input voxel.

**Comment by XuyangBai** [comment]
Thanks a lot！
