### ISSUE TITLE
Any plans for LRP implementation?

### ISSUE THREAD

**Issue by edraizen** [facebookresearch/SparseConvNet#147]
I know this isn't a SparseConvNet specific question, but I was wondering it you've done LRP with it and have any examples. I would like to use it on the UNet model.

My first thought would be to add SparseConvNet functions into an existing pytorch LRP library such as https://github.com/moboehle/Pytorch-LRP. However, that library doesn't seem very complete, e.g. I am not sure how to add deconvolutions or other LRP rules. If you have any suggestions, I'd like to know.

Thanks!

**Comment by btgraham** [comment]
Sorry, but I don't know enough about LRP to usefully comment. To convert a dense UNet to a sparse one, you basically swap 
Convolutions with size 3, stride 1, padding 1 with sparseconvnet.SubmanifoldConvolutions,
Convolutions with size 3 or 2, stride 2 with sparseconvnet.Convolutions,
Transpose convolutions with sparseconvnet.Deconvolutions.
The same might be true for LRP?

**Comment by edraizen** [comment]
I am now in the process of adding scn into Pytorch-LRP. However, when I try to invert a `SubmanifoldConvolution` (the last module of the Unet) using a `DeconvolutionFunction`, I get an empty tensor output.

The model is a Unet with dimension=3, reps=1, nPlanes=[32, 64, 96, 128, 160], residual_blocks=True, downsample=[2,2], and spatial_size=[264,264,264].

Here is a portion of the lrp code:
```python
def relprop(relevance_in, original_layer, original_input_tensor, original_output_tensor, lrp_exp=1, eps=1e-6):
    """"Modified from https://github.com/moboehle/Pytorch-LRP/blob/master/inverter_util.py#L378"""
    original_input_tensor.features = original_input_tensor.features.pow(lrp_exp).detach()
    weight = original_layer.weight.pow(lrp_exp).detach() #torch.Size([27, 1, 32, 32]
    norm = scn.submanifoldConvolution.SubmanifoldConvolutionFunction.apply(
            original_input_tensor.features, weight, torch.Tensor(), m.metadata,
            m.in_spatial_size, m.dimension, m.filter_size) #torch.Size([8619, 32])
    norm = norm + torch.sign(norm) * eps
    relevance_in[norm == 0] = 0
    norm[norm == 0] = 1
    normalized_relevence = relevance_in/norm #torch.Size([8619, 32])
    relevance_out = scn.deconvolution.DeconvolutionFunction.apply(
            normalized_relevence, weight, torch.Tensor(), m.metadata,
            original_output_tensor.spatial_size, #Use output size as input size?
            original_input_tensor.spatial_size, #Use input size as output size?
            m.dimension, m.filter_size, toLongTensor(m.dimension, 1) ) #tensor([], size=(0, 32))
    relevance_out *= m.in_tensor #Errors here
    return relevance_out
```
> RuntimeError: The size of tensor a (0) must match the size of tensor b (8619) at non-singleton dimension 0

The last SubmanifoldConvolution has the same nIn and nOut, so I am not sure if a Deconvolution as an inverse makes sense if always creates a larger spatial size with `(input.spatial_size - 1) * self.filter_stride + self.filter_size`.

If you have any insight into the correct parameters for DeconvolutionFunction as well as how to make it have the correct output size, I'd appreciate it!

**Comment by bugsuse** [comment]
@edraizen Hi, I also want to apply LRP for unet model, and test some tools but almost unsupport `nn.Upsample` or `nn.ConvTranspose2d` layer.  Have you already achieved it for unet model?
