### ISSUE TITLE
sudo sh develop.sh, got some error

### ISSUE THREAD

**Issue by shishanmeng** [facebookresearch/SparseConvNet#150]
running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
building 'sparseconvnet.SCN' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/sparseconvnet
creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN
/usr/local/cuda/bin/nvcc -I/usr/local/include -I/home/ssm/SparseConvNet-master/sparseconvnet/SCN/ -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: type name is not allowed

sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: expected an expression

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: type name is not allowed

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: expected an expression

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: type name is not allowed

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: expected an expression

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: type name is not allowed

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: expected an expression

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: type name is not allowed

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: expected an expression

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: type name is not allowed

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: expected an expression

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: type name is not allowed

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: expected an expression

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: type name is not allowed

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: expected an expression

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: type name is not allowed

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: expected an expression

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: type name is not allowed

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: expected an expression

54 errors detected in the compilation of "/tmp/tmpxft_00007c76_00000000-6_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by bottler** [comment]
Could this be using a compiler which is too old - e.g. doesn't have full support for C++11 lambdas?

**Comment by defenceVT** [comment]
> running develop
> running egg_info
> creating sparseconvnet.egg-info
> writing sparseconvnet.egg-info/PKG-INFO
> writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
> writing top-level names to sparseconvnet.egg-info/top_level.txt
> writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> package init file 'sparseconvnet/SCN/**init**.py' not found (or not a regular file)
> reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> running build_ext
> building 'sparseconvnet.SCN' extension
> creating build
> creating build/temp.linux-x86_64-3.6
> creating build/temp.linux-x86_64-3.6/sparseconvnet
> creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN
> /usr/local/cuda/bin/nvcc -I/usr/local/include -I/home/ssm/SparseConvNet-master/sparseconvnet/SCN/ -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
> sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(628): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(628): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(628): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(636): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(636): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(636): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(653): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(653): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(653): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(661): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(661): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(661): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: expected an expression
> 
> 54 errors detected in the compilation of "/tmp/tmpxft_00007c76_00000000-6_cuda.cpp1.ii".
> error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

I meet the same problem， have you solve the problem?

**Comment by defenceVT** [comment]
> running develop
> running egg_info
> creating sparseconvnet.egg-info
> writing sparseconvnet.egg-info/PKG-INFO
> writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
> writing top-level names to sparseconvnet.egg-info/top_level.txt
> writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> package init file 'sparseconvnet/SCN/**init**.py' not found (or not a regular file)
> reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> running build_ext
> building 'sparseconvnet.SCN' extension
> creating build
> creating build/temp.linux-x86_64-3.6
> creating build/temp.linux-x86_64-3.6/sparseconvnet
> creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN
> /usr/local/cuda/bin/nvcc -I/usr/local/include -I/home/ssm/SparseConvNet-master/sparseconvnet/SCN/ -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
> sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(628): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(628): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(628): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(636): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(636): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(636): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(653): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(653): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(653): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(661): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(661): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Convolution.cu(661): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: expected an expression
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: a pointer to a bound function may only be used to call the function
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: type name is not allowed
> 
> sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: expected an expression
> 
> 54 errors detected in the compilation of "/tmp/tmpxft_00007c76_00000000-6_cuda.cpp1.ii".
> error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

@shishanmeng,  I meet the same problem, have you solve the problem?

**Comment by shishanmeng** [comment]
> Could this be using a compiler which is too old - e.g. doesn't have full support for C++11 lambdas?

Thank you. I'll upgrade the compiler and try again

**Comment by shishanmeng** [comment]
> > running develop
> > running egg_info
> > creating sparseconvnet.egg-info
> > writing sparseconvnet.egg-info/PKG-INFO
> > writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
> > writing top-level names to sparseconvnet.egg-info/top_level.txt
> > writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> > package init file 'sparseconvnet/SCN/**init**.py' not found (or not a regular file)
> > reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> > writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
> > running build_ext
> > building 'sparseconvnet.SCN' extension
> > creating build
> > creating build/temp.linux-x86_64-3.6
> > creating build/temp.linux-x86_64-3.6/sparseconvnet
> > creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN
> > /usr/local/cuda/bin/nvcc -I/usr/local/include -I/home/ssm/SparseConvNet-master/sparseconvnet/SCN/ -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
> > sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: expected an expression
> > sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: expected an expression
> > sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: expected an expression
> > sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: expected an expression
> > sparseconvnet/SCN/CUDA/Convolution.cu(628): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/Convolution.cu(628): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/Convolution.cu(628): error: expected an expression
> > sparseconvnet/SCN/CUDA/Convolution.cu(636): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/Convolution.cu(636): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/Convolution.cu(636): error: expected an expression
> > sparseconvnet/SCN/CUDA/Convolution.cu(653): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/Convolution.cu(653): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/Convolution.cu(653): error: expected an expression
> > sparseconvnet/SCN/CUDA/Convolution.cu(661): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/Convolution.cu(661): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/Convolution.cu(661): error: expected an expression
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: expected an expression
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: expected an expression
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: expected an expression
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: expected an expression
> > sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: expected an expression
> > sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: expected an expression
> > sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: expected an expression
> > sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: expected an expression
> > sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: expected an expression
> > sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: a pointer to a bound function may only be used to call the function
> > sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: type name is not allowed
> > sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: expected an expression
> > 54 errors detected in the compilation of "/tmp/tmpxft_00007c76_00000000-6_cuda.cpp1.ii".
> > error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
> 
> @shishanmeng, I meet the same problem, have you solve the problem?

Not yet

**Comment by kvhq** [comment]
What is your version of pytorch? I had such an issue. I've upgraded to 1.3.1 and everything started working smoothly. By the way it may be a duplicate - https://github.com/facebookresearch/SparseConvNet/issues/132
