### ISSUE TITLE
Setup.py is using unsupported C++ version?

### ISSUE THREAD

**Issue by Navhkrin** [facebookresearch/SparseConvNet#151]
Im not sure about the details of this issue, but i was getting build errors following given instructions, but i was able to successfully build after changing following line on setup.py 

`extra = {'cxx': ['-std=c++11', '-fopenmp'], 'nvcc': ['-std=c++11', '-Xcompiler', '-fopenmp']}`
to
`extra = {'cxx': ['-std=c++14', '-fopenmp'], 'nvcc': ['-std=c++14', '-Xcompiler', '-fopenmp']}`

**Comment by bottler** [comment]
It would be interesting to know which compiler/version you are using and what the errors were. Such a change won't break anything though.

**Comment by btgraham** [comment]
setup.py updated for newer versions of pytorch, thanks.
