### ISSUE TITLE
DepthWise Convolution

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/SparseConvNet#153]
Hey there,

Do you plan to implement DepthWise Convolution as MixConv could be extremely interesting to try out there.

Best,
T.C

**Comment by LeonhardFeiner** [comment]
I think that depthwise convolutions are equal to grouped convolutions, where the number of channels is equal to the number of groups, isn't it?
The feature of grouped convolutions has been added to the framework last year. Have you tried it?

I would be interested if grouped convolutions work properly, as past tests with my network did not. However, I didn't spend a lot of effort in trying to fix it ;)

**Comment by btgraham** [comment]
SubmanifoldConvolution takes a 'groups' argument.  Setting groups=number of input units=number of output units will give you depthwise convolutions. I don't recommend this as the computation would be very I/O bound.
