### ISSUE TITLE
How to get larger values at the output

### ISSUE THREAD

**Issue by aniqueakhtar** [facebookresearch/SparseConvNet#157]
I am using SparseConvNet for a new task which is different from Segmentation. I need the output as xyz coordinates so my output dimension is 3. My input ``full_scale=4096``. I want my outputs to be between 0 and full_scale. However, my outputs are always between -1 and 1. I am wondering which part of the code is restricting my output from going large and giving me results between 0 and full_scale.

```
class Model(nn.Module):
    def __init__(self):
        nn.Module.__init__(self)
        self.sparseModel = scn.Sequential().add(
           scn.InputLayer(data.dimension,data.full_scale, mode=4)).add(
           scn.SubmanifoldConvolution(data.dimension, 3, m, 3, False)).add(  # The 2nd input here is the dimension of the features.
           scn.UNet(data.dimension, block_reps, [m, 2*m, 3*m, 4*m, 5*m, 6*m, 7*m], residual_blocks)).add(
           scn.BatchNormReLU(m)).add(
           scn.OutputLayer(data.dimension))
        self.linear = nn.Linear(m, data.output_dim)
    def forward(self,x):
        x=self.sparseModel(x)
        x=self.linear(x)
        return x
```

Any help would be appreciated.
Thanks

**Comment by aniqueakhtar** [comment]
I changed it to something like this for now:

```
class Model(nn.Module):
    def __init__(self):
        nn.Module.__init__(self)
        self.sparseModel = scn.Sequential().add(
           scn.InputLayer(data.dimension,data.full_scale, mode=4)).add(
           scn.SubmanifoldConvolution(data.dimension, 3, m, 3, False)).add(  # The 2nd input here is the dimension of the features.
           scn.UNet(data.dimension, block_reps, [m, 2*m, 3*m, 4*m, 5*m, 6*m, 7*m], residual_blocks)).add(
           scn.BatchNormReLU(m)).add(
           scn.OutputLayer(data.dimension))
        self.linear = nn.Linear(m, data.output_dim)
    def forward(self,x):
        x=self.sparseModel(x)
        x=self.linear(x)
        return x*data.full_scale
```

It is training, I'll see if it is able to converge.

**Comment by btgraham** [comment]
What is the meaning of the coordinates you are trying to predict?

**Comment by aniqueakhtar** [comment]
I am doing something like point cloud denoising where the output coordinates should be slightly different from input coordinates.

**Comment by btgraham** [comment]
Instead of trying to predict the coordinates, try to predict the change in the coordinates between input and output. That will play much better with ConvNets as it might be expected to be translation invariant.

**Comment by aniqueakhtar** [comment]
Yes. I can confirm. I predicted the change in coordinates and added them to my input to get the final output. I can confirm that it is converging. 
I can use this architecture for denoising. Now I would try to use this network for other tasks like upsampling, impainting, registration, super resolve, etc
