### ISSUE TITLE
 Is it possible to find a way to make all computations on GPU ?

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/SparseConvNet#158]
Dear All,

I was wondering if there would be an way to make all computations on GPU, or at least speeding up the computation, as it is currently a bottleneck for trying out more complex models.

Best regards,
Thomas Chaton.

**Comment by btgraham** [comment]
What do you mean by more complex models? How does the run time change when model complexity increases?

**Comment by tchaton** [comment]
Dear @btgraham, 

Currently the sparseconv model I am training takes 30 min / epoch on my custom data. It converges in 5 days with pretty good results. I have tried more complex architectures, but I am getting training time around 2 h / epoch, which is too much.

However, I was wondering if you had any idea on how to make SpareConv faster ? And if a complete GPU based implementation would be possible ?

Best,
Thomas Chaton.

**Comment by tchaton** [comment]
Hey @btgraham, 

I am wondering if you have ideas on how to overcome the current bottleneck of this framework to make training / inference faster, scale to millions of points( 1M, 10M, 100M maybe) with the lowest memory consumption.

Best regards,
Thomas Chaton.

**Comment by btgraham** [comment]
You can use checkpointing to reduce memory usage during training.
i.e. take a section of the network and put it in a CheckpointedSequential unit.
https://github.com/facebookresearch/SparseConvNet/blob/master/sparseconvnet/sequential.py
i.e take a stack of residual units and wrap them.
