### ISSUE TITLE
Questions about the input of sparse convolution

### ISSUE THREAD

**Issue by rex-lei-jpg** [facebookresearch/SparseConvNet#160]
Hi,
I have a doubt that the input of a sparse convolution should be a sparse tensor. However, if the dense tensor and the sparse tensor are concated, can the mixed tensor be obtained using sparse convolution to continue the operation?

**Comment by baifanxxx** [comment]
It's interesting.

**Comment by btgraham** [comment]
The input has to be prepared as a SparseConvNetTensor. Please see the examples.
