### ISSUE TITLE
What would be an ideal scale and full_scale values

### ISSUE THREAD

**Issue by aniqueakhtar** [facebookresearch/SparseConvNet#163]
I am trying to optimize my training and preprocessing of data. I am currently editing data.py
My input point cloud is already whole (integer) numbers so I am using scale as 1. I am using these values:
```
scale = 1
full_scale = 64
```

I want to ask, would it give me better results if I multiple both of them with a power of 2. E.g. this:
```
scale = 1*2*2
full_scale = 64*2*2
```

Would this give better results? I would like to understand how full_scale and scale affects the network.

Thank you.

**Comment by btgraham** [comment]
Sorry for the delay. If your input has integer coordinates, you don't need to scale up.
full_scale can be as big as you want to fit in the largest possible input.
