### ISSUE TITLE
Install Error ！

### ISSUE THREAD

**Issue by AnsonYanxin** [facebookresearch/SparseConvNet#164]
Environment：Ubuntu 16.04 + Cuda 9.0 + Cudnn 7.0 + python3.7 + pyTorch 1.1

When i run "python setup.py install",  i got the errors as follow:
----------------------------------------------------------------------------------------
sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: a pointer to a bound function may only be used to call the function
sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: type name is not allowed
sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: expected an expression
...
sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: a pointer to a bound function may only be used to call the function
sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: type name is not allowed
sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: expected an expression
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
----------------------------------------------------------------------------------------
So, what should i do to fix all the problems?

**Comment by bottler** [comment]
I think Cuda 9.0 is too old to build SparseConvNet.

**Comment by AnsonYanxin** [comment]
> I think Cuda 9.0 is too old to build SparseConvNet.

Thank you for your suggestion！ It do fixed my problems！
I update Cuda to 10.1 and Pytorch to 1.4
