### ISSUE TITLE
convolution for multi channel

### ISSUE THREAD

**Issue by xianglizhi123** [facebookresearch/SparseConvNet#168]
Hello,
I have problem about doing convolution with multi channels. I know how to construct the input when the input image has one channel from your example code.
for batchIdx, msg in enumerate(msgs):
    for y, line in enumerate(msg):
        for x, c in enumerate(line):
            if c == 'X':
                locations.append([y, x, batchIdx])
                features.append([1])
But if I want to add channel index,for example I have an input image with B=2,C=128,H=7,W=7, how can I construct the input data with my example?
Thank you

**Comment by mawanda-jun** [comment]
Hi, 
if you still need some help, I understood the following.
Coming from your image and taking the first image of your batch, you should compute the index of nonzero values. Therefore, taking your example and said
`image.shape :>> (64, 64, 3)`  (say 3 color channels)
you can extract the indices with:
`indices = torch.nonzero(image, as_tuple=True)`
In this way you get the nonzero indices from your image.
After that, you can retrieve the values with:
`values = image[indices[0:-1]]` and your values will have dimension `(6059, 3)`
Which is good for the description of `scn.InputLayer`:

> coords is 2d torch.LongTensor with size `(N x dimension (batch size == 1))`
or `N x (dimension+1)`  (first d columns are coordinates, last column is batch index)
features is a CPU or CUDA float tensor with size
`(N x n_feature_planes)`

And your `values` tensor has the `n_feature_planes` dimension set to 3.

Does it help?

**Comment by xianglizhi123** [comment]
Thanks for your reply, it helps me a lot.
