### ISSUE TITLE
Inaccurate spatial_size calculation in "sparseconvnet/convolution.py"

### ISSUE THREAD

**Issue by junzel** [facebookresearch/SparseConvNet#169]
Hi, thank you for the public source code. I am trying to re-write ResNet18 into this sparse version. To save the time, I used the provided SparseResNet module as implemented in `examples/Assamese_handwriting/ResNet.py.` My input spatial size I pass into the `scn.InputLayer()` is [101, 101]. However, it keeps returning me:

```bash
File "/home/junzel/Projects/Sparse/sparseconvnet/convolution.py", line 38, in forward
    self.filter_size == input.spatial_size).all(), (input.spatial_size,output.spatial_size,self.filter_size,self.filter_stride)
AssertionError: (tensor([50, 50]), tensor([24, 24]), tensor([3, 3]), tensor([2, 2]))
```

The assertion is at line 38 of `sparseconvnet/convolution.py,` which is:

```python
assert ((output.spatial_size - 1) * self.filter_stride +
                self.filter_size == input.spatial_size).all(), (input.spatial_size,output.spatial_size,self.filter_size,self.filter_stride)
```

It is obvious that this assertion is to make sure the calculated output spatial size matches the input spatial size. My `input.spatial_size` here is [50, 50], and the `output.spatial_size` calculated by a line of code right above is [24, 24]. Other related varialbes include `self.filter_stride` is 2 and `self.filter_size` is 3. So, in the assertion line, we have 50 != 49, which is caused by floor((50 - 3) / 2) + 1, where (50 - 3) / 2 is 23.5. In this case, I guess the calculated `output.spatial_size` can never match the `input.spatial_size', unless these sizes are carefully crafted. 

To solve this issue, from my experiments, changing the original assertion to the following works:

```python
assert (((output.spatial_size - 1) * self.filter_stride + self.filter_size == input.spatial_size).all()) or \
            (((output.spatial_size - 0.5) * self.filter_stride + self.filter_size == input.spatial_size).all()), \
                (input.spatial_size,output.spatial_size,self.filter_size,self.filter_stride)
```

I'll try to make a pull request later. Hope this solves others' similar troubles.

Cheers,
Junze

**Comment by btgraham** [comment]
The input spatial size must be compatible with the convolution size and stride.
If size=3 and stride=2, then the input must have the form 2k+3 for some integer k.

**Comment by junzeliu** [comment]
> The input spatial size must be compatible with the convolution size and stride.
> If size=3 and stride=2, then the input must have the form 2k+3 for some integer k.

Does it mean that the convolutional layers (and MaxPooling layers) cannot be applied directly to ImageNet and CIFAR-100, which have data of size 224x224 and 32x32 respectively? Is it expected to apply a padding operation before feeding the images into these layers?
