### ISSUE TITLE
Import Error:

### ISSUE THREAD

**Issue by mmderakhshani** [facebookresearch/SparseConvNet#17]
Hi there, I have installed your amazing library with the following command (on Pytorch):

```
sudo apt-get install libsparsehash-dev
python setup.py develop
```
I think the library was installed correctly, but when I want to import sparseconvnet package, the error bellow has happened:

`ImportError: /home/mohammad/SparseConvNet-master/PyTorch/sparseconvnet/SCN/_SCN.so: undefined symbol: _ZNSt12length_errorC1EPKc
`

Could you please help me how can I solve this problem?

**Comment by btgraham** [comment]
Sorry you are having problems.
What version of Ubuntu are you using?
One possible solution may be to install PyTorch inside a conda environment (download from https://conda.io/miniconda.html) and then run 'python setup.py develop' in the conda environment.
Ben

**Comment by mohammad-py** [comment]
Thanks for your response Mr. @btgraham. The Ubutntu version of mine is 16.04. My installation procedure is as same as your suggestion. I have installed the Anaconda and then create a virtual environment called sparse in that and activate it using `source activate sparse`. Then I have run following commands
`
sudo apt-get install libsparsehash-dev
git clone git@github.com:facebookresearch/SparseConvNet.git
cd SparseConvNet/PyTorch/
python setup.py develop
`
I think the installation did not have any problems and also no warnings and errors. But when I want to import **sparseconvnet** for example in an ipython, it generates the aforementioned error.

**Comment by btgraham** [comment]
Hmm. Can you please try taking the attached file, and moving it to PyTorch/setup.py (so remove the .txt from the filename) and rerunning 'python setup.py develop' command.

[setup.py.txt](https://github.com/facebookresearch/SparseConvNet/files/1485148/setup.py.txt)

**Comment by mohammad-py** [comment]
@btgraham, Same error as above.

**Comment by lawrencekiba** [comment]
Hi @btgraham,

I now have the same issue with the current repo version. I am using Ubuntu 18.04 & installing on conda with Python 3.7

**Comment by lawrencekiba** [comment]
> _ZN3c105ErrorC1ENS_14SourceLocationERKSs

Resolved by reinstalling PyTorch
