### ISSUE TITLE
How to perform upsampling or employ encoder decoder architecture without submanifold or active sites?

### ISSUE THREAD

**Issue by aniqueakhtar** [facebookresearch/SparseConvNet#171]
Hello,
I want to create multiple different architectures and I had a few questions. If anyone can answer each of the questions individually, that would be really beneficial.

1) Suppose I use a full_scale value of 64. My input number of points is 10k but I want the output of the network to be 64x64x64 = 262144 points. Is it possible to do so?

2) How can I create an encoder-decoder architecture where the decoder does not know the active sites from the encoder part of the network?

3) Is it possible to upsample a latent feature into a scale that is not seen by the network before?

4) If I don't have features and give them as 1s, would the network be able to learn based on only the geometry of the point cloud?

Thank you so much!

**Comment by btgraham** [comment]
1. You can use a SparseToDense layer.
2. and 3. You can use a FullConvolution and the a Sparsify Layer. But you need to define a loss that correctly identifies which locations should be active.
4. Probably yes.
