### ISSUE TITLE
What is the difference from O-CNN?

### ISSUE THREAD

**Issue by abc-def-g** [facebookresearch/SparseConvNet#175]
I am new to the field of 3D deep learning. After some literature survey, I find that the key idea of the so-called `Submanifold Sparse Convolution` is exactly the same as the `O-CNN (published in Siggraph 2017, July 2017)`:  i.e. constraining the computation to a submanifold of the 3D volume, and maintaining the active voxels unchanged.

In the published CVPR 2018 paper, the authors missed this important reference, right? Correct me, if my understanding is wrong.

**Comment by btgraham** [comment]
The CVPR 2018 paper was an extension of previous work (https://arxiv.org/abs/1706.01307 ) that was contemporaneous with O-CNN. We obviously missed the O-CNN reference.
