### ISSUE TITLE
What does downsmaple mean in UNet or FullyConvolutionalNet mean?

### ISSUE THREAD

**Issue by chenerg** [facebookresearch/SparseConvNet#176]
`scn.UNet(dimension, reps, nPlanes, residual_blocks=False, downsample=[2,2]))`

UNet should preserve its size, if there is downsample, where is the upsample?

**Comment by btgraham** [comment]
It is the size and stride used for downsampling in the UNet. The same values are used for the upsampling.
If size=2, stride=2, the input spatial size should be even. If size=3, stride=2, the input size should be odd.
