### ISSUE TITLE
Proper usage of scn.ConcatTable?

### ISSUE THREAD

**Issue by andrewcking** [facebookresearch/SparseConvNet#177]
I am trying to implement my own simple sparse fully convolutional model with SparseConvNet and with this am trying to understand the proper usage of (and reasoning behind) scn.ConcatTable. 

Typically in PyTorch one would simply concatenate the output tensors from two layers and continue to pass it forward as a new single tensor. I realize that with sparse nets this is complicated by the fact that they operate on tensors of both features and indices. Could one use the typical torch.concat with two sparse tensors: concatenating their indices and features together to create a new input layer which is then passed forward? Would this operate the same as concatTable? I see concatTable being used in the examples but I can't seem to parse out its usage or meaning very well just from looking at them and I don't see it in the docs. Any direction or advice anyone can give would be very helpful.

**Comment by btgraham** [comment]
It is just a container (similar to torch.nn.Sequential) but for storing parallel computation branches used to build ResNet-style blocks or U-Net style residual connections. It is typically followed by an AddTable or JoinTable module. For examples see networkArchitectures.py

It is based on the old LuaTorch containers. The more modern PyTorch-y approach it to create torch.nn.Modules that contain the submodules you want to run.
