### ISSUE TITLE
Jupyter lab integration

### ISSUE THREAD

**Issue by evinpinar** [facebookresearch/SparseConvNet#178]
the test script 'hello-world.py' works perfectly, but I cannot run the same script on jupyter lab. I think there is an issue with pybind, but I could not resolve it. Basically, it gives these errors:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-58cf1bc3c527> in <module>
      4 
      5 # Use the GPU if there is one and sparseconvnet can use it, otherwise CPU
----> 6 use_cuda = torch.cuda.is_available() and scn.SCN.is_cuda_build()
      7 device = 'cuda:0' if use_cuda else 'cpu'
      8 if use_cuda:

AttributeError: module 'sparseconvnet.SCN' has no attribute 'is_cuda_build'`

`~/Documents/sparse_conv/SparseConvNet/sparseconvnet/metadata.py in Metadata(dim)
     15 
     16 def Metadata(dim):
---> 17     return getattr(sparseconvnet.SCN, 'Metadata_%d'%dim)()

AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_2'`

**Comment by bottler** [comment]
I suspect this is to do with the python environment in jupyter lab and on the command line being different. Is jupyter running in the same conda environment/virtual environment as where you run python on the command line? Do you have the same sys.path in both places?

**Comment by evinpinar** [comment]
Yes they run in the same virtual environment, from the main directory. I can run the hello world from there, but I copy-pasted the same things to a notebook. I also added the directory: sys.path.append("../sparseconvnet")

**Comment by bottler** [comment]
`sys.path.append("../sparseconvnet")` shouldn't be necessary. `hello_world.py` should be working without it, as should the lab. Something is wrong which persuaded you to add it.

**Comment by evinpinar** [comment]
I mean it does not work without it also. What did you mean by "Do you have the same sys.path in both places?"?

**Comment by bottler** [comment]
My question about sys.path is now irrelevant - I thought your only problem was a discrepancy between lab and command line. Now I see that `hello_world.py` doesn't really work. What happens when you restore `hello_world.py` and run `bash develop.sh`?

**Comment by evinpinar** [comment]
Yes lab also works now after doing that. Thanks!
