### ISSUE TITLE
NYU coords and matrix m, what is happening?

### ISSUE THREAD

**Issue by evinpinar** [facebookresearch/SparseConvNet#179]
Hi, I do not understand these steps of NYU example, which are basically some operations on coordinates: 

` m=torch.eye(3)
theta=torch.rand(1).item()*0.2-0.1
m[0,0]=math.cos(theta)
m[0,2]=math.sin(theta)
m[2,0]=-math.sin(theta)
m[2,2]=math.cos(theta)
m/=downscale
 m+=torch.FloatTensor(3,3).uniform_(-0.05,0.05)
if torch.rand(1).item()<0.5:
    m[:,0]*=-1
coords=torch.matmul(coords,m)
coords+=torch.rand(3)*24000-12000+32768`

**Comment by btgraham** [comment]
A 3x3 matrix is built for data augmentation purposes (rotation, stretching).
Then the coordinates are multiplied by the matrix and shifted to a random location in a cube of size (2^16)^3, which is the convolutional network's receptive field.

**Comment by evinpinar** [comment]
Thanks! Another question is to retrieve the solution back for visualization reasons. Do you have an available code for that? So, to visualize the predicted segmentation mask, we need to decode predictions back by using coordinates (augmented or not).

**Comment by evinpinar** [comment]
Hi again! When we don't do data augmentation operations on coordinates, sometimes jupyter kernel crashes. What might be the reason for that?
