### ISSUE TITLE
NYU coordinates data augmentation

### ISSUE THREAD

**Issue by evinpinar** [facebookresearch/SparseConvNet#180]
How can we revert the data augmentation on coordinates (multiplication with m, rotation etc...) in order to visualize the predicted mask?

**Comment by btgraham** [comment]
It is not relevant for showing the predicted output.
Each batch is made up of a list of pixels, with the order determined here:
https://github.com/facebookresearch/SparseConvNet/blob/aa071d62ad2fc59d5fbd08fd17a9153f3f720984/examples/nyu2/data/prepare_data.py#L95
Just reshape the output to shape [batch_size,width,height,n_classes] to visualize.
