### ISSUE TITLE
Submission to ScanNet server

### ISSUE THREAD

**Issue by azuki-miho** [facebookresearch/SparseConvNet#182]
Hello! Thanks for your work.
I am interested in your work and want to follow it. Can you provide the script which uses the trained model to give the prediction on the test dataset of ScanNet.
Thanks

**Comment by btgraham** [comment]
The expression  'store.max(1)[1].numpy()' 
https://github.com/facebookresearch/SparseConvNet/blob/aa071d62ad2fc59d5fbd08fd17a9153f3f720984/examples/ScanNet/unet.py#L84
gives the predictions for the whole dataset concatenated. The variable 'valOffsets' in data.py 
https://github.com/facebookresearch/SparseConvNet/blob/aa071d62ad2fc59d5fbd08fd17a9153f3f720984/examples/ScanNet/data.py#L98
shows how to chop the tensor up into individual scenes.
