### ISSUE TITLE
spconv Tensor and SparseConvNet tensor

### ISSUE THREAD

**Issue by victoryc** [facebookresearch/SparseConvNet#183]
I am trying to convert some code built upon [spconv](https://github.com/traveller59/spconv) to use SparseConvNet instead. One place I am stuck is with the construction of the sparse tensor. The code for creating spconv's SparseConvTensor looks as follows:

`spconv.SparseConvTensor(input.features, input.indices, input.spatial_shape, input.batch_size)`

What would be the equivalent constructor for SparseConvNetTensor? 

Thanks.

**Comment by btgraham** [comment]
My preferred solution is to use InputLayer or BLInputLayer: for examples see
https://github.com/facebookresearch/SparseConvNet/blob/master/examples/hello-world.py
It can be used with OutputLayer/BLOutputLayer to deal with points falling in the same voxel, i.e.
https://github.com/facebookresearch/SparseConvNet/blob/aa071d62ad2fc59d5fbd08fd17a9153f3f720984/examples/ScanNet/unet.py#L25

InputLayer takes a list of locations (including the batch index) and features, 
i.e. a (n,d+1) LongTensor and a (n,f) Float Tensor.
BLInputLayer takes a (-1)-padded 3D tensor of locations and features, 
i.e. a (batch_size,n,d) LongTensor and a (batch_size,n,f) Float Tensor.
