### ISSUE TITLE
Sparseconvnet compilation error in pytorch 1.1

### ISSUE THREAD

**Issue by sumo-agarwal** [facebookresearch/SparseConvNet#187]

**Comment by sumo-agarwal** [comment]
Can we import Sparseconvnet libraries in pytorch 1.1 or 1.2. I suffered compilation error of setup.py file both on pytorch 1.1 and 1.2.

**Comment by btgraham** [comment]
Sorry, but the pytorch API changes, so SparseConvNet can only support the most recent version.
