### ISSUE TITLE
error when install SparseConvNet on Ubuntu18.04

### ISSUE THREAD

**Issue by WaitLover** [facebookresearch/SparseConvNet#189]
hello, I got some problem when run the command: zsh devolope.sh.
the detial is as follow:
running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
building 'sparseconvnet.SCN' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/sparseconvnet
creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN
/usr/local/cuda/bin/nvcc -I/home/jin/Documents/SparseConvNet/SparseConvNet/sparseconvnet/SCN/ -I/home/jin/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/jin/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/jin/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/jin/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/jin/anaconda3/include/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++14 -Xcompiler -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: type name is not allowed

sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: expected an expression

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: type name is not allowed

sparseconvnet/SCN/CUDA/ActivePooling.cu(62): error: expected an expression

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: type name is not allowed

sparseconvnet/SCN/CUDA/AveragePooling.cu(40): error: expected an expression

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: type name is not allowed

sparseconvnet/SCN/CUDA/AveragePooling.cu(73): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(628): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(636): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(653): error: expected an expression

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: type name is not allowed

sparseconvnet/SCN/CUDA/Convolution.cu(661): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(578): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(586): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(603): error: expected an expression

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: type name is not allowed

sparseconvnet/SCN/CUDA/Deconvolution.cu(611): error: expected an expression

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: type name is not allowed

sparseconvnet/SCN/CUDA/MaxPooling.cu(39): error: expected an expression

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: type name is not allowed

sparseconvnet/SCN/CUDA/MaxPooling.cu(73): error: expected an expression

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: type name is not allowed

sparseconvnet/SCN/CUDA/SparseToDense.cu(34): error: expected an expression

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: type name is not allowed

sparseconvnet/SCN/CUDA/SparseToDense.cu(66): error: expected an expression

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: type name is not allowed

sparseconvnet/SCN/CUDA/UnPooling.cu(36): error: expected an expression

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: a pointer to a bound function may only be used to call the function

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: type name is not allowed

sparseconvnet/SCN/CUDA/UnPooling.cu(67): error: expected an expression

54 errors detected in the compilation of "/tmp/tmpxft_0000691f_00000000-6_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

cuda10.0, cudnn7.6.5, pytorch1.0.0
Could you have a look and see where goes wrong?
thanks a lot

**Comment by bottler** [comment]
pytorch 1.0.0 is too old. See #187.
