### ISSUE TITLE
how to write to metadatas?

### ISSUE THREAD

**Issue by etienne87** [facebookresearch/SparseConvNet#19]
At some point I need to filter out all zeros values (and their corresponding locations). Is there a workaround to modify the metadatas of a sparse tensor?

**Comment by btgraham** [comment]
Let x be a SparseConvNetTensor.
Extract the features and list of locations+batchIndices using
xi=x.getSpatialLocations()
xf=x.features
Pick a subset of the rows from xi and xf and create a new SparseConvNetTensor:
yi=torch.index_select(xi,0,subset)
yf=torch.index_select(yi,0,subset)
y=scn.InputBatch(dimension, spatial_size)
y.setLocations(yi,torch.Tensor(yf.shape))
y.features=yf  #Preserve autograd continuity

**Comment by etienne87** [comment]
thanks!
