### ISSUE TITLE
Is it possible to remove the excess active sites created as a result of many convolutions

### ISSUE THREAD

**Issue by andrewcking** [facebookresearch/SparseConvNet#193]
Is there an easy way to retrieve only the original active sites after performing a series of sparse convolutions? In other words I would like to be able to remove the excess active sites (locations and features) created as a result of many convolutions.

I realize submanifoldconvolution exists to keep the active sites constant but it may not be optimal for my use case.

**Comment by btgraham** [comment]
If you have one active site in a 4x4 grid
```
....
.x..
....
....
```
and you do a 2x2 convolution, the output pattern of active sites is
```
xx.
xx.
...
```
The number of active sites has increased (as you don't use a submanifold convolution). How do you decide which of the 4 new active locations is attached to the original active site?

**Comment by andrewcking** [comment]
Unless I’m missing something, that problem isn’t unique to sparse convolution and has more to do with even kernel lengths than anything else (an even kernel could cause minor localization error in dense semantic segmentation for instance if unhandled).

If you do 2 3x3 convolutions on a 5x5 you are left with a 1x1 grid traditionally corresponding to the inner pixel in the original. If you pad the tensor (by increasing its spatial shape in spaseconvnets case) you can have the original 5x5. 

Additionally, won’t the resulting spaseconvtensor have an active site with the same reported spatial location as before (which one could manually extract)? Or does it reindex after convolution?
