### ISSUE TITLE
Is the Transpose Convolutions available?

### ISSUE THREAD

**Issue by dengyuhk** [facebookresearch/SparseConvNet#194]
Hi authors, I am reading your work "Unsupervised learning with sparse space-and-time autoencoders".  I'm curious about the novel transpose convolution in SparseConvNet, but it seems not finished yet.

**Comment by btgraham** [comment]
For example see
https://github.com/facebookresearch/SparseConvNet/blob/159e5f9a2349c776c422dce9f5b4493519303dc2/sparseconvnet/networkArchitectures.py#L203
