### ISSUE TITLE
Convolution layer types

### ISSUE THREAD

**Issue by ShilinC** [facebookresearch/SparseConvNet#195]
Hi,

In addition to "SubmanifoldConvolution" layer, there are also "FullConvolution" layer and "Convolution" layer. I know "SubmanifoldConvolution" is the submanifold sparse conv, but what are "FullConvolution" and "Convolution"?

**Comment by btgraham** [comment]
https://arxiv.org/pdf/1711.10275.pdf
Convolution (SC) is greedy; it is active if any input in the convolutional filter is active.
FullConvolution==TransposeConvolutions are used to build UNets (c.f. torch.nn.ConvTranspose2d).
