### ISSUE TITLE
Use 2d or 3d Convolution for image data with missing pixels.

### ISSUE THREAD

**Issue by samblack15** [facebookresearch/SparseConvNet#196]
I'd like to to try and train a sparse CNN to classify images that have missing pixel values, like so:

![image](https://user-images.githubusercontent.com/31870152/97056442-0549e900-1557-11eb-9198-f15758ae8cfa.png)

I'm unsure if this calls for 2D or 3D convolutions, as these are 2D images of 3D scenes. Obviously, with a regular CNN, I'd use regular 2D convolutions, but wanted to double-check the same applies here. Thanks.

**Comment by btgraham** [comment]
Unless you have depth infomation somehow, it is just 2D. If >=50% of the pixels are present, I would use partialconv https://github.com/NVIDIA/partialconv .
