### ISSUE TITLE
Type mismatch error in example code

### ISSUE THREAD

**Issue by angup143** [facebookresearch/SparseConvNet#20]
I get the following error when I try to run the torch examples:

> ...sparseconvnet/SparseToDense.lua:39: bad argument #1 to 'size' (torch.CudaTensor expected, got boolean)

Stack Trace:

> In 1 module of nn.Sequential:
In 4 module of sparseconvnet.Sequential:
...ch/install/share/lua/5.2/sparseconvnet/SparseToDense.lua:39: bad argument #1 to 'size' (torch.CudaTensor expected, got boolean)
stack traceback:
	[C]: in function 'size'
	...ch/install/share/lua/5.2/sparseconvnet/SparseToDense.lua:39: in function <...ch/install/share/lua/5.2/sparseconvnet/SparseToDense.lua:31>
	[C]: in function 'xpcall'
	/home/aa/torch/install/share/lua/5.2/nn/Container.lua:63: in function 'rethrowErrors'
	...torch/install/share/lua/5.2/sparseconvnet/Sequential.lua:41: in function <...torch/install/share/lua/5.2/sparseconvnet/Sequential.lua:32>
	[C]: in function 'xpcall'
	/home/aa/torch/install/share/lua/5.2/nn/Container.lua:63: in function 'rethrowErrors'
	/home/aa/torch/install/share/lua/5.2/nn/Sequential.lua:44: in function </home/aa/torch/install/share/lua/5.2/nn/Sequential.lua:41>
	(...tail calls...)
	...re/lua/5.2/sparseconvnet/ClassificationTrainValidate.lua:57: in function 'ClassificationTrainValidate'
	VGGplus.lua:35: in main chunk
	[C]: in function 'dofile'
	...aa/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

Pytorch examples run without any problems. Would you have any insight on this?

Conversely, do you have Pytorch examples for ModelNet40?

**Comment by btgraham** [comment]
Now fixed. Thanks for the report.

**Comment by angup143** [comment]
Thanks!
