### ISSUE TITLE
Group normalization with sparse convolution

### ISSUE THREAD

**Issue by victoryc** [facebookresearch/SparseConvNet#200]
I see that SparseConvNet has implementation for batch normalization. Is it possible to use group normalization with SparseConvNet?

My specific use case is the following. As of now, I am using the U-Net class available in SparseConvNet. But, it uses batch normalization. I would like try out group normalization instead.

Thanks.

**Comment by btgraham** [comment]
Added as sparseconvnet.SparseGroupNorm
