### ISSUE TITLE
import  sparseconvnet error

### ISSUE THREAD

**Issue by pupil011** [facebookresearch/SparseConvNet#205]
in this code ,i can't find sparseconvnet.py .
can you provide it again?

**Comment by bottler** [comment]
There is no `sparseconvnet.py`. `sparseconvnet` is a package not a module. It is a directory containing an `__init__.py` file. If you have installed SparseConvNet (this repository) then you should not have a problem.

**Comment by pupil011** [comment]
thanks ,i got it
