### ISSUE TITLE
What is the usage of spatialSize? 

### ISSUE THREAD

**Issue by Clarence-gsx** [facebookresearch/SparseConvNet#206]
Wanna do further research with SCN.

I might have problem understanding the usage of inputSpatialSize.

In the example Helloworld.py:

"inputSpatialSize = model.input_spatial_size(torch.LongTensor([10, 10]))
input_layer = scn.InputLayer(2, inputSpatialSize)"

the spatialsize determines the output size.

But in example/3d_segmentation/Unet, what does data.spatialSize do?

Trying to figure the meaning of spatial size so that I can set it according to different dataset.

Really appreciate your work.

Best,
Gu

**Comment by btgraham** [comment]
It is the theoretical size of the grid. It can change between different layers. i.e. pooling makes it smaller. 
For a UNet, the input size is the same as the output size.
