### ISSUE TITLE
How to add Factional Max Pooling(FMP) to SparseConvNet?

### ISSUE THREAD

**Issue by lifematrix** [facebookresearch/SparseConvNet#21]
Hey, your FMP and Sparse convolution network are very inspiring. I read your code published for kaggle winner solution. Thank a lot.

I want to implement a model in PyTorch using both  of them. I note the FMP python wrapper ```torch.nn.FractionalMaxPool2d``` has been included in latest PyTorch release. 

Can you give any example?

Thanks,

Steven

**Comment by btgraham** [comment]
PyTorch includes a dense version of FMP. I have not added a spare version to this repository yet, but it is implented in the 'old' SparseConvNet (https://github.com/btgraham/SparseConvNet).

If you are learning about dense ConvNets, an excellent place to start is with ResNets:
https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
