### ISSUE TITLE
Active output site 

### ISSUE THREAD

**Issue by Dibbya40** [facebookresearch/SparseConvNet#212]
Hello. Thank you for this amazing work. I had a question. From the paper, "we restrict an output site to be active if and only if the site at the corresponding site in the input is active". Could you please tell me where exactly it is in the code? Thank you so much.

**Comment by btgraham** [comment]
It is related to the logic here:
https://github.com/facebookresearch/SparseConvNet/blob/master/sparseconvnet/SCN/Metadata/SubmanifoldConvolutionRules.h
