### ISSUE TITLE
CPU usage is too high

### ISSUE THREAD

**Issue by Shaoyi0520** [facebookresearch/SparseConvNet#218]
I transfer the network and data to the GPU while training, but the CPU usage is still high. I tested and found that it is caused by Input LayerFunction and Submanifoldconvolutionfunction. Please how can I reduce CPU usage and use GPU to accelerate training？
![Snipaste_2022-01-13_12-13-25](https://user-images.githubusercontent.com/60254694/149297359-8a95aa46-7cc1-4345-a3a9-5561f5e91d4a.png)

**Comment by btgraham** [comment]
Hello. The more points in the point cloud the slower it will be unfortunately.
Voxelizing the network at lower resolution, but making the network deeper will shift the balance from CPU to GPU.
SpConv or MinkowskiEngine may be able to do more of the work on the GPU.
