### ISSUE TITLE
File "/home/libo/SparseConvNet/sparseconvnet/denseToSparse.py", line 58, in forward     aa = aa.view(-1, input.size(1)) RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by bobonpu1** [facebookresearch/SparseConvNet#220]
File "/home/libo/SparseConvNet/sparseconvnet/denseToSparse.py", line 58, in forward
    aa = aa.view(-1, input.size(1))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by btgraham** [comment]
What is the input that is causing it to fail?
I have swapped .view to .reshape ...

**Comment by bobonpu1** [comment]
The input is the batch of images. with the shape of (B,C,H,W). I utilize the contiguous() before put it to the DenseToSparse(), but it doesn't work.

**Comment by bobonpu1** [comment]
> What is the input that is causing it to fail?
> I have swapped .view to .reshape ...

Is it right to use DenseToSparse Layer like this?
