### ISSUE TITLE
how to transfer batch of (B,C,H,W) to sparse tensor? DenseToSparse()?

### ISSUE THREAD

**Issue by bobonpu1** [facebookresearch/SparseConvNet#221]
the data are in the form of (B,C,H,W). I would like to transfer it to the sparse tensor. If is it right to use DenseToSparse() directly?

**Comment by btgraham** [comment]
If the input is actually spatially-sparse (i.e. you have columns of C zeros in the input tensor) you can do that.
Although depending on how the input is formed, it might be more efficient to use InputLayer (https://github.com/facebookresearch/SparseConvNet#hello-world)
