### ISSUE TITLE
File "/home/libo/SparseConvNet/sparseconvnet/maxPooling.py", line 85, in forward     self.pool_size == input.spatial_size).all() AssertionError   Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by bobonpu1** [facebookresearch/SparseConvNet#222]

**Comment by bobonpu1** [comment]
It seems that if I sweap the .view to .reshape in the line 58 of denseToSparse. I will meet this error.

**Comment by bobonpu1** [comment]
assert ((output.spatial_size - 1) * self.pool_stride +
                self.pool_size == input.spatial_size).all()

Why no padding?

**Comment by btgraham** [comment]
Padding is not supported; but you can just make the input grid bigger as needed.
The input should be compatible with the size and stride, i.e. if size=2 and stride=2, then the input size should be even.
