### ISSUE TITLE
can't get the same results in paper

### ISSUE THREAD

**Issue by shuchao97** [facebookresearch/SparseConvNet#224]
hello, author. thanks to your code. Recently, when I implemented the code, I found that the training results were worse than the data provided by the original paper. Is it because of the following warning during the training process?
/home/charles/sparseconvnet/convolution.py:36: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  (input.spatial_size - self.filter_size) // self.filter_stride + 1
Train in NVIDIA GeForce RTX 3060(12g), cuda=11.3, cudnn=8.2, pytorch=1.10. 
Thanks, looking forward to your reply
@likethesky @Celebio @colesbury @bottler @pdollar

**Comment by btgraham** [comment]
What result are you trying to replicate?
