### ISSUE TITLE
About the parameters of InputLayer

### ISSUE THREAD

**Issue by Hazeliii** [facebookresearch/SparseConvNet#228]
Hi Benjamin, thanks for your release.
I couldn't figure out the parameters of the _InputLayer_, especially the _spatial_size_. Would you please tell me what's the meaning of  these parameters?  Is it related to the output ? Thanks.

**Comment by yxKryptonite** [comment]
Me neither.
Have anyone of you figured out what spatialSize means? I'm really confused.

**Comment by btgraham** [comment]
A dense ConvNet operates on tensors with shape (B,C,H,W) where B is the batch size, C is the number of channels, and HxW is the spatial size of the input. The input_layer in https://github.com/facebookresearch/SparseConvNet/blob/main/README.md#hello-world
takes the spatial size as a parameter, to know how big the input grid will be. The input spatial size is typically 2 or 3 dimensional. It can be very large is 2**30 x 2**30 x 2**30 if the input is very sparse,
