### ISSUE TITLE
convolution with groups?

### ISSUE THREAD

**Issue by etienne87** [facebookresearch/SparseConvNet#23]
Is there a way for applying convolution with groups to implement a sparse Xception or ResNeXT model? 

I think this would be useful since sparsity is often greater considering the entire volume of features rather than just spatial sites.

**Comment by btgraham** [comment]
Group convolutions are not implemented yet, but will be.
One drawback IMHO is that in 3D or 4D, memory tends to be a bigger limitation than compute.
Group convolutions tend to be used to trade higher memory usage for less compute.
