### ISSUE TITLE
voxel input

### ISSUE THREAD

**Issue by HirojiFukuyama** [facebookresearch/SparseConvNet#232]
Hi!
Suppose I have a voxel file and I wanna do semantic segmentation on it. After I load the file and turn it into a 3D array (or tensor), how can I feed the 3D array into the network (let's say the `scn.SubmanifoldConvolution` module)? 
When I directly feed it in, the error indicates that Tensor doesn't have a `feature` attribute, so how can I convert this 3D array to adapt to your API?
Thanks for any reply!

**Comment by btgraham** [comment]
An example of preparing the input it here:
https://github.com/facebookresearch/SparseConvNet/blob/main/README.md#hello-world
