### ISSUE TITLE
 undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

### ISSUE THREAD

**Issue by samanemami** [facebookresearch/SparseConvNet#234]
I am trying to install the library after cloning it directly from GitHub, but it gives me the following error;

```log
linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv
```

Note that I went through the following issues and reinstalled the PyTorch, but it did not work.
I am working with Ubuntu.

issue #225, issue #17

Any help would be more valuable

**Comment by jiangdabornin2002** [comment]
oh,me too! Undefined symbol,have you fix it ? I am looking forward to some help.

**Comment by NorthTree22** [comment]
Hi, have you save this problem? I face the same confusion.
