### ISSUE TITLE
'getSpatialLocations' return strange values

### ISSUE THREAD

**Issue by zjhthu** [facebookresearch/SparseConvNet#24]
I use `getSpatialLocations()` to get the locations of features, but I find the returned values contain many (0,0,0,0). However, locations should be unique and not repeat.
I trace the codes, and I think  this [line](https://github.com/facebookresearch/SparseConvNet/blob/master/PyTorch/sparseconvnet/SCN/generic/Geometry/Metadata.cpp#L120) and this [line](https://github.com/facebookresearch/SparseConvNet/blob/master/PyTorch/sparseconvnet/SCN/generic/Geometry/Metadata.cpp#L122) should be changed to 
`lD[(it->second + SGs[i].ctr) * (Dimension + 1) + d] = it->first[d];` 
`lD[(it->second + SGs[i].ctr)* (Dimension + 1) + Dimension] = i;`
Otherwise, locations of latter sample will overwrite locations of previous sample, and this will left many values in `lD` not be written.

**Comment by btgraham** [comment]
Thanks for the very detailed report. I hope my push fixes it.
Best wishes
Ben
