### ISSUE TITLE
question from paper

### ISSUE THREAD

**Issue by hfutdzx** [facebookresearch/SparseConvNet#245]
hello，thank you for your contribution，but i have a question when i read your paper. 

“hidden layers in the network may not receive all the information they require to classify the input data: in particular, two neighboring connected components are treated completely independently”

i can’t understand this sentence which are from your paper.

why do hidden layers treat neighboring connected components completely independently？

**Comment by btgraham** [comment]
'Submanifold convolutions' pass messages only amongst immediate neighbors, and only if they are active.
Downscaling and then upscaling space with a UNet allows distant parts of the input to get signals from each other; once you downscale enough everything becomes connected.

**Comment by hfutdzx** [comment]
Thank you, I have understanded it. Components do not refer to pixel or point
