### ISSUE TITLE
ValidConvolution generates same features twice

### ISSUE THREAD

**Issue by chrischoy** [facebookresearch/SparseConvNet#30]
When I changed the example `hello-world.py`

```
msg = [
" X  "
"XXX "
"    "]
```
Then forwarding the input to one `ValidConvolution` generates 8 features not 4, and it results in exact duplicates.

```
scn.ValidConvolution(2, 1, 7, 3, False)(input)

SparseConvNetTensor<<Variable containing:
 0.8005  1.0915  0.1243  0.2239 -2.0065  2.4473  0.7704
-0.0807  0.8334  0.7881  0.9474 -1.2600  0.9929  1.4385
-0.9909  0.2812 -0.8543  0.7658 -1.7169  1.6085  1.5675
-0.7380 -0.0175 -1.5790  0.8088 -0.6446  1.7917 -0.0282
 0.8005  1.0915  0.1243  0.2239 -2.0065  2.4473  0.7704
-0.0807  0.8334  0.7881  0.9474 -1.2600  0.9929  1.4385
-0.9909  0.2812 -0.8543  0.7658 -1.7169  1.6085  1.5675
-0.7380 -0.0175 -1.5790  0.8088 -0.6446  1.7917 -0.0282
[torch.FloatTensor of size 8x7]
<<Metadata:dim=2, p=94189934691952>>
 12
  9
[torch.LongTensor of size 2]
>>
```

The first 4 rows and rows 5-8 are exactly the same features.
Within the ValidConvolutionRule.h, the rulebook contains a duplicate rule for features 4-7.

```
(gdb) p rules
$1 = std::vector of length 9, capacity 9 = {
std::vector of length 4, capacity 4 = {0, 3, 4, 7},
std::vector of length 4, capacity 4 = {0, 2, 4, 6},
  std::vector of length 4, capacity 4 = {0, 1, 4, 5},
  std::vector of length 8, capacity 8 = {2, 3, 1, 2, 6, 7, 5, 6},
  std::vector of length 16, capacity 16 = {3, 3, 1, 1, 2, 2, 0, 0, 7, 7, 5, 5, 6, 6, 4, 4}, 
  std::vector of length 8, capacity 8 = {2, 1, 3, 2, 6, 5, 7, 6},
  std::vector of length 4, capacity 4 = {1, 0, 5, 4},
  std::vector of length 4, capacity 4 = {2, 0, 6, 4},
  std::vector of length 4, capacity 4 = {3, 0, 7, 4}}
```

Is there a reason for computing the exact same features twice?

**Comment by DiligentPanda** [comment]
hi, in the example, there are two identical samples in the batch. I guess this is the reason.

**Comment by btgraham** [comment]
As Diligent Panda say, hello-world.py shows two ways to add points. 
Try changing msg after line 46, before line 48 to create a minibatch with two different samples.

Use the SparseConvNetTensor.getSpatialLocations() method to understand how the lines in the output of the ValidConvolution correspond to spatial locations.

By the way, regarding the contents of rules that you print out using gdb:
The 9 entries correspond to the 9 locations in a 3x3 convolutional filter, but they are independent of the number of feature planes.

'std::vector of length 4, capacity 4 = {0, 3, 4, 7}' means that
input spatial location 0 contributes to output location 3, and
input spatial location 4 contributes to output location 7

Regards
Ben

**Comment by chrischoy** [comment]
Ah right. I overlooked the bath size part. It makes sense now. Thanks!
