### ISSUE TITLE
Tiny Bugs and Questions in Convolution and Deconvolution

### ISSUE THREAD

**Issue by DiligentPanda** [facebookresearch/SparseConvNet#31]
Hi, thanks for your awesome framework. I really want to apply it in my own 3D detection problem.

I notice some potential bugs when I reading the source code.

The first one is
https://github.com/facebookresearch/SparseConvNet/blob/112745755b7681690225c1cddef69b83b3744a14/PyTorch/sparseconvnet/convolution.py#L57-L64
Line 57- Line 60 seem to be redundant and worse, `bias` is actually not defined.

Another one is 
https://github.com/facebookresearch/SparseConvNet/blob/112745755b7681690225c1cddef69b83b3744a14/PyTorch/sparseconvnet/deconvolution.py#L129-L130
According to my understanding, this function should output expected input size given output size. The calculation here seems to belong to _convolution_, not _deconvolution_. 

And possibly, spatial size checking should be added to make sure the inputs to `JoinTable` and `AddTable` are compatible.

Finally, I have some questions about `deconvolution`.
1. How _deconvoution_ decides its active sites of output. Does it retrieve the `rulebook` saved earlier, which is generated by a former convolution of the same spatial size.
2. Take segmentation as an example, if my whole network are built by this _sparse_ framework, does it mean that both of my input and output are sparse?

**Comment by btgraham** [comment]
Thank you very much for the bug reports, I have pushed what is hopefully a fix.
```
import torch
import sparseconvnet as scn

net=scn.Sequential(
  ).add(scn.Convolution(2, 3, 8, 3, 2, True)
  ).add(scn.Convolution(2, 8, 16, 5, 3, True))
input_spatial_size=net.input_spatial_size(torch.LongTensor([1,1]))
print(input_spatial_size)
net.add(scn.Deconvolution(2, 16, 8, 5, 3, True)).add(
        scn.Deconvolution(2, 8, 3, 3, 2, True))
print(net.input_spatial_size(input_spatial_size))
assert (net.input_spatial_size(input_spatial_size)==input_spatial_size).all()
```

Regarding your questions:
1) Yes. The deconvolutions must match up with a previous convolution, as in the examples above. The Metadata object keeps track of the required information.
2) Yes, see for example  https://github.com/facebookresearch/SparseConvNet/blob/master/PyTorch/sparseconvnet/networkArchitectures.py#L209 and https://arxiv.org/pdf/1711.10275.pdf
This can be used for example to classify a sparse collection of voxels, e.g. an airplane into wings, engines, tail and body.

Regards
Ben
