### ISSUE TITLE
Install on OSX

### ISSUE THREAD

**Issue by BastiaanBergman** [facebookresearch/SparseConvNet#32]
Does anyone have any hints for how to install on OSX?
`brew install google-sparsehash`
Seems to install the required `libsparsehash-dev` library.
(and `pip3 install cffi` was needed for cffi)
But `python setup.py develop` gives me errors like:

```
./generic/Geometry/../32bits.h:30:9: error: cannot initialize a variable of type 'long *' with an rvalue of type 'int64_t *' (aka 'long long *')
  long *td = THLongTensor_data(t);
        ^    ~~~~~~~~~~~~~~~~~~~~
```
I believe this has to do with the C compiler used, but not sure how to change the one used. Any hints are very welcome!

Platform:
OSX 10.13
Python 3.6
PyTorch 0.3.1
no GPU

**Comment by kenorb** [comment]
For macOS, install libsparsehash via: `brew install google-sparsehash`
