### ISSUE TITLE
Any suggestion or plan for speeding up hash table operation?

### ISSUE THREAD

**Issue by zjhthu** [facebookresearch/SparseConvNet#37]
I find it takes a long time on CPU when the number of input points is large, though I have used `precomputeMetaData` and OMP. Most of the time is spent on the hash table operation, because `libsparsehash` runs on CPU and we process these data one-by-one.

I think it might be a common case in large-scale 3D CNN applications, so do you have any suggestion or plan for speeding up hash table operation? Such as using GPU-based hash table [`CUDPP`](http://cudpp.github.io/cudpp/2.2/hash_overview.html), though I know it might not be an easy task to reimplement this project with `CUDPP`.

**Comment by btgraham** [comment]
precomputeMetaData is only useful in certain situations (i.e. with a muti threaded data loader), so it might be faster not to use it.

Do you have an example that you consider slow? What kind of network? What is a typical input point?

Also, I recently tweaked the compilation options, so are you using the latest version of SparseConvNet?

**Comment by zjhthu** [comment]
I use multi-thread data loader provided in your examples. My input is TSDF values converted from depth map, each sample may contain more than 1 million points, my network is posted in previous [issue](https://github.com/facebookresearch/SparseConvNet/issues/18). It takes me about 5 days with an Intel E5-2650 v3 CPU @ 2.30GHz for training, and about 3 days with an E5-2680 v2 CPU @ 2.80GHz. GPU is usually often idle during training. 
Though I have finished the previous project, I am wondering if I can speed up CPU operations for my further research.
Need I provide a sample?
Also, I am using an early version SparseConvNet.
