### ISSUE TITLE
Questions about implementing muti-branches network architecture.

### ISSUE THREAD

**Issue by daihengming** [facebookresearch/SparseConvNet#38]
I'm trying use Torch7 to implement a network that has muti-branches and applies its ith child module to the ith slice of the input.  Since the input of the sparse convnet must be an  'InputBatch', I tried the Container nn.ParallelTable(), and put several 'InputBatch' into a table as the final input to the nn.ParallelTable(). But I got some error in backward procedure in function 'updateGradInput' where you made an annotation ' just call backward'.I'm not quiet sure what to do, should I just call 'backward' after your annotation?  I tried this but got some other errors.Or should I implement a new ParallelTable which has 'backward' function?

**Comment by btgraham** [comment]
The Torch7 version of SparseConvNet only supports calling backward, not calling updateGradInput and updateGradWeight separately.

I strongly recommend using the PyTorch version of SparseConvNet. For an example of a network with branches, please see https://github.com/facebookresearch/SparseConvNet/blob/f2e3800bb89fa195e48105156e356b6d9d4650ca/PyTorch/sparseconvnet/networkArchitectures.py#L138

**Comment by daihengming** [comment]
Thanks for your reply!@btgraham I've checked the definition of SparseResNet that you offered in the PyTorch version of SparseConvNet, and I see that the ConcatTable is used to create branches, but I actually want to build an architecture just like nn.ParallelTable for several different input, but I didn't see any layer that is similar to ParallelTable in Torch version of SparseConvNet, neither in PyTorch version. I'm wondering if you are thinking to add ParallelTable layer to the SparseConvNet or is there another way to implement same architecture? Cause I think it is very useful in building a network. Could you please give me more suggestion?

**Comment by btgraham** [comment]
In PyTorch, you can define the network by combing simple modules with python code to define the forward pass, see for example: https://github.com/pytorch/vision/blob/1a6038eaa5aeafbb46c78a5d57d9a42e3d90f1f7/torchvision/models/resnet.py#L25
