### ISSUE TITLE
How to use SparseConvNet in the Imagenet data?

### ISSUE THREAD

**Issue by fengxiuyaun** [facebookresearch/SparseConvNet#39]
@btgraham Hi, I am very interested in your paper "Spatially-sparse convolutional neural networks",too. But 1.  I don't know how to implement the network that trains Imagenet data by using “ facebookresearch/SparseConvNet”, beacuse of the fact how images are as the input of networks.
2. what's  the different between sparse comv and original conv?
3. why is it improved that using sparseconv on the imagenet or kaggle diabetic data?
thank you!

**Comment by AutumnWormSun** [comment]
@fengxiuyaun Constructing input is critical. But how to construct multi-channels input? Do u get some idea?

**Comment by btgraham** [comment]
For ImageNet and other 'dense' 2d picture datasets, see for example https://github.com/pytorch/examples/tree/master/imagenet
