### ISSUE TITLE
Examples for U-net

### ISSUE THREAD

**Issue by akturtle** [facebookresearch/SparseConvNet#40]
I'm pretty interesting how to construct a U-net with SparseConv. Would you mind provide an example of sparse U-net?

**Comment by btgraham** [comment]
Thanks for the interest. I will be adding examples soon.

**Comment by yashasvi97** [comment]
Hi @btgraham. 
Thanks for the code!
It would be interesting to look how SparseConvNets could be applied with U-net. Any progress on this front?
