### ISSUE TITLE
Empty output when using scn.Deconvolution

### ISSUE THREAD

**Issue by ICEORY** [facebookresearch/SparseConvNet#44]
Hi! I'm trying to use the deconvolution layer, but I got an empty output.
My code is:
```
import torch, sparseconvnet as scn
deconv = scn.Deconvolution(2, 1, 1, 3, 1, False).cuda()
print(deconv.weight)
input=scn.InputBatch(2, 5)
input.add_sample()
input.set_location(torch.LongTensor([1, 1]), torch.FloatTensor([1]), 0)
input.set_location(torch.LongTensor([2, 3]), torch.FloatTensor([1]), 0)
input.set_location(torch.LongTensor([3, 2]), torch.FloatTensor([1]), 0)
input.cuda()
print(deconv(input))
```
Then I got the result:
```
Parameter containing:
tensor([[[-0.2356]],

        [[-0.5641]],

        [[-0.6885]],

        [[ 0.0216]],

        [[-1.1243]],

        [[ 0.3640]],

        [[-0.2336]],

        [[ 0.1309]],

        [[-0.4607]]], device='cuda:0')
SparseConvNetTensor<<features=tensor([], device='cuda:0')coordinates=tensor([], dtype=torch.int64)spatial size=tensor([ 7,  7])>>
```
I use pytorch 0.4 and cuda 9.0. 
Thanks for your help!

**Comment by btgraham** [comment]
scn.Deconvolution has to be matched up with a scn.Convolution (see https://github.com/facebookresearch/SparseConvNet/blob/master/sparseconvnet/networkArchitectures.py#L245)
The scn.Convolution is applied with stride>=2, and then the scn.Deconvolution reverses the change to the set of active sites.
i.e.
https://github.com/facebookresearch/SparseConvNet/raw/master/img/img_stridedConv_conv_deconv.gif
