### ISSUE TITLE
Installing/Building in docker (running with cuda)

### ISSUE THREAD

**Issue by jewfro-cuban** [facebookresearch/SparseConvNet#45]
I encounter an issue when the installation instructions are part of a Dockerfile.
When using docker build, everything seems ok during build but at run time (docker run --runtime=nvidia ...) trying to run the hello_world.py example yields segmentation fault.

Though nvcc should be able to build without dependency in the driver runtime, I've made 2 tests:

1) If I manually re-install/build SparseConvNet after running the container with --runtime=nvidia, the hello_world example runs fine. 
2) Doing the same by running the container but this time without --runtime=nvidia and manually re-installing/building SparseConvNet, yields segmentation fault upon running the hello-world example

Has anyone had an issue building into a docker image?

**Comment by jewfro-cuban** [comment]
nope.

**Comment by jeff-engineml** [comment]
I was able to get this working by replacing this line:
https://github.com/facebookresearch/SparseConvNet/blob/b596b10752136cd805b3b3f0507ac2a2e2d414fc/setup.py#L31 with `if True else` before building.

**Comment by btgraham** [comment]
Sorry, I am afraid I know nothing about docker so I can't help .
