### ISSUE TITLE
Error when using second GPU

### ISSUE THREAD

**Issue by schmohlo** [facebookresearch/SparseConvNet#46]
Hello,

I have 2 GPUs in my computer. When I want to use the second one for a SCN, I get errors similar to:

> RuntimeError: cublas runtime error : library not initialized at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/THCGeneral.cpp:411
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCTensorCopy.c line=70 error=77 : an illegal memory access was encountered

Simple code:
```
import torch
import torch.nn as nn
import sparseconvnet as scn

device = 'cuda:1'  # doesn't work for the scn model
# device = 'cuda:0'  # does work
# device = 'cpu'     # does work

class Model_SCN(nn.Module):

    def __init__(self):
        nn.Module.__init__(self)

        inputSpatialSize = [32, 32, 32]
        dimension = 3
        self.sparseModel = scn.Sequential().add(
           scn.InputLayer(dimension, inputSpatialSize, mode=2)).add(
           scn.OutputLayer(dimension))

    def forward(self, x):
        x = self.sparseModel(x)
        return x

class Model(nn.Module):

    def __init__(self):
        nn.Module.__init__(self)

        self.fc1 = nn.Linear(2, 2)

    def forward(self, x):
        x = self.fc1(x)
        return x

model = Model()
model = model.to(device)
model_scn = Model_SCN()
model_scn = model_scn.to(device)

coords = torch.tensor([[0, 0, 0], [1, 0, 0]], device=device, dtype=torch.long)
features = torch.tensor([[1], [1]], device=device, dtype=torch.float)

output_scn = model_scn((coords, features))
output = model(features.squeeze())
```

Normal PyTorch nets as well as SCNs on cpu or cuda:0 work just fine.
I'm using python 3.5, cuda9.0 and pytorch0.4.0 on ubuntu.

**Comment by btgraham** [comment]
Hello, instead of calling `.to(device)`, please try calling
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```
_before_ importing Torch/SparseConvNet. Then only the second GPU will be visible to PyTorch. Does that work?

**Comment by schmohlo** [comment]
Hello, 

thank you for your reply.

This indeed does work ('cuda:0' is now referring to the second gpu, while 'cuda:1' is now a invalid device)
