### ISSUE TITLE
3d_segmentation ShapeNet: scaling x 4 

### ISSUE THREAD

**Issue by roma-goodok** [facebookresearch/SparseConvNet#49]
Hi! 
I am a little confused with the following line:
https://github.com/facebookresearch/SparseConvNet/blob/master/examples/3d_segmentation/data.py#L80

> xl=np.floor(resolution*(**4**+xl)).astype('int64')

It looks like input points first were transposed far from zero point and are scaled after. As the result all samples are placed far from center.
While, in the paper described that each point cloud centered and re-scaled to fit into a sphere with diameter 4S. 

Is it ok that point clouds are not centered? Or to  guarantee that all values are positive?

**Comment by btgraham** [comment]
The convolutional networks receptive field is of the form [0,sz]-cubed, so the input coordinates need to be non-negative. 
L43: The objects are scaled to fit the unit sphere.
L79: Objects are shifted randomly for data augmentation.
L80: Objects are scaled up and translated by [4*resolution,4*resolution,4*resolution].
