### ISSUE TITLE
Other datasets preprocessing

### ISSUE THREAD

**Issue by b04902036** [facebookresearch/SparseConvNet#51]
Thank you for your great work!
I now want to use your SparseConvnet to construct a `mobilenetv1` for testing on my own dataset, and the images in this dataset is indeed sparse (in fact it is wafer dataset, and I have binarized to make them sparse). 
What I want to ask is, it seems that I have to pass a tuple `(coords, features, batch_size [optional])` to `scn.InputLayer`, however I don't really understand what they are.
Are `coords` the coordinates point to those active sites (foreground points) ?
Then what is features which is of size `N x n_feature_planes` ?
Thank you very much!

**Comment by btgraham** [comment]
coords contains rows like (x-coordinate, y-coodinate, minibatch-index) and 
features contains rows like (red-value, green-value, blue-value).
The number of rows should match.

In two dimensions, unless the active sites are very localised, you may be better off using a conventional dense convnet (i.e. PyTorch Conv2d) as only the first few layers will be sparse.
