### ISSUE TITLE
Support for python 2.7

### ISSUE THREAD

**Issue by shashanktyagi** [facebookresearch/SparseConvNet#54]
Is there a plan to support python 2.7?

**Comment by btgraham** [comment]
Not really, but it is probably just a question of adding `from __future__ import print_function` in a few files if you want to try that.

**Comment by shashanktyagi** [comment]
I did that already and was able to build successfully. Thanks!

**Comment by dhaivat666** [comment]
@shashanktyagi hey, I am trying to get it to work with python 2.7 due to some system constraints. I know it's an old issue but do you happen to remember/know where are we supposed to make changes to get it to work with python 2.7?

**Comment by shashanktyagi** [comment]
@dhaivat666 As I recall I added just a few `__future__` imports. You can check out the following utility to do the same - https://pypi.org/project/3to2/

**Comment by HaiwangYu** [comment]
I was able to make it work with python 2.7 by adding `from __future__ import print_function` to `sparseconvnet/utils.py`

SparseConvNet: 159e5f9
python: 2.7.15
torch: 1.3.1
torchvision: 0.4.2
cuda: 10.1
