### ISSUE TITLE
22 errors detected in the compilation of "/tmp/tmpxft_00001a9c_00000000-6_cuda.cpp1.ii".

### ISSUE THREAD

**Issue by vyshakhullas** [facebookresearch/SparseConvNet#55]
Hi, 

I get the following error after running bash build.sh. Working on Ubuntu 16.04, Python 3.6 and Pytorch-1.0. Any idea how I could solve this?

Thank you! 

sparseconvnet/SCN/CUDA/ActivePooling.cu(26): error: no instance of overloaded function "at::TypeExtendedInterface::tensor" matches the argument list
            argument types are: ({...})
            object type is: at::TypeExtendedInterface

sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: type name is not allowed

sparseconvnet/SCN/CUDA/ActivePooling.cu(27): error: expected an expression

sparseconvnet/SCN/CUDA/ActivePooling.cu(61): error: no instance of overloaded function "at::TypeExtendedInterface::tensor" matches the argument list
            argument types are: ({...})
            object type is: at::TypeExtendedInterface

22 errors detected in the compilation of "/tmp/tmpxft_00001a9c_00000000-6_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by btgraham** [comment]
ATen's API seems to have changed. I have pushed an update, tested against pytorch-nightly build.
Hope that helps.
Ben

**Comment by vyshakhullas** [comment]
Thank you for your quick response. But now the error has changed to the following:

 ^
/usr/include/c++/6/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor>&&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor, at::Tensor}]’:
/usr/include/c++/6/tuple:686:422:   required by substitution of ‘template<class ... _UElements, class _Dummy, typename std::enable_if<((std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1ul == 1)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_NonNestedTuple<tuple<_Elements ...>&&>()), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple<_Args1 ...>&&) [with _UElements = {at::Tensor, at::Tensor, at::Tensor, at::Tensor}; _Dummy = void; typename std::enable_if<((std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1ul == 1)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_NonNestedTuple<tuple<_Elements ...>&&>()), bool>::type <anonymous> = <missing>]’
/home/vyshakh/anaconda2/envs/py36torch041/lib/python3.6/site-packages/torch/lib/include/ATen/Functions.h:3509:107:   required from here
/usr/include/c++/6/tuple:495:244: error: wrong number of template arguments (5, should be 2)
       return  __and_<__not_<is_same<tuple<_Elements...>,
                                                                                                                                                                                                                                                    ^    
/usr/include/c++/6/type_traits:1558:8: note: provided for ‘template<class _From, class _To> struct std::is_convertible’
     struct is_convertible
        ^~~~~~~~~~~~~~
/usr/include/c++/6/tuple:502:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor>&&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

Vyshakh

**Comment by btgraham** [comment]
Hmm, what is your torch version? 
  [i.e. run python -c 'import torch; print(torch.__version__)' , I tested using 1.0.0.dev20181017]
And gcc version?  [gcc --version; tested with gcc 5.4 inside anaconda]

**Comment by vyshakhullas** [comment]
I have the same pytorch version. But gcc is 6.4. Maybe I should try with 5.4?
