### ISSUE TITLE
AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_2'

### ISSUE THREAD

**Issue by poodarchu** [facebookresearch/SparseConvNet#56]
I've fixed the above problem.
But now I got trouble with sparseconvnet, after I compile it with gcc 5.4 and pytorch 1.0, it said:
Installed /data-sdb/benjin.zhu/libs/anaconda3.6/lib/python3.6/site-packages/sparseconvnet-0.2-py3.6-linux-x86_64.egg Processing dependencies for sparseconvnet==0.2 Finished processing dependencies for sparseconvnet==0.2

but then I tried python examples/hello-world.py, I got
$ python examples/hello-world.py Traceback (most recent call last): File "examples/hello-world.py", line 30, in <module> input = scn.InputBatch(2, inputSpatialSize) File "/data-sdb/benjin.zhu/second/SparseConvNet/sparseconvnet/inputBatch.py", line 19, in __init__ self.metadata = Metadata(dimension) File "/data-sdb/benjin.zhu/second/SparseConvNet/sparseconvnet/metadata.py", line 17, in Metadata return getattr(sparseconvnet.SCN, 'Metadata_%d' % dim)() AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_2'

This stucks me for a long time.

**Comment by btgraham** [comment]
Thanks for the report. 
Can you try running 'bash develop.sh', please. 
Are there any error messages?
Ben

**Comment by YiruS** [comment]
I have the same problem. Fixed by running 'bash develop.sh'. So what is the difference then? Thanks!

**Comment by btgraham** [comment]
Hmm, running  `python setup.py install` seems to be failing to install properly, but `python setup.py develop` works?
