### ISSUE TITLE
TriangLeNet

### ISSUE THREAD

**Issue by justusschock** [facebookresearch/SparseConvNet#57]
Hi,

in your Paper "Sparse 3D convolutional neural networks" you stated that you have compared a network with triangular kernels against a kernel with quadric kernels.

Is there any implementation of the triangular version available for PyTorch or could you give some hints towards how to implement it?

Thanks!

**Comment by btgraham** [comment]
I have not implemented triangular convolutions exactly, but there are hexagonal convolutions, which are kind of on a triangular lattice.
https://github.com/facebookresearch/SparseConvNet/blob/master/sparseconvnet/permutohedralSubmanifoldConvolution.py

If you want to experiment with triangular convolutions for dense 2d images, the easiest thing is to use regular PyTorch conv2d convolutions with some of the weights fixed to zero, forming a triangular receptive field.
