### ISSUE TITLE
1*1*1 scn.Convolution return an empty tensor (tensor([]))

### ISSUE THREAD

**Issue by bigsheep2012** [facebookresearch/SparseConvNet#59]
I tried 1*1*1 3d sparse convolution and returns an empty tensor
Here's an example:
    dim = 3
    output_shape = [10, 20, 30]
    scn_input = scn.InputLayer(3, output_shape)
    scn_conv1 = scn.Convolution(dim, 128, 64, (1, 1, 1), (1,1,1), bias=False)
    scn_todense = scn.SparseToDense(dim, 64)

    voxels = torch.randn(500,128)
    coorsx = np.arange(30)
    coorsy = np.arange(20)
    coorsz = np.arange(10)
    np.random.shuffle(coorsx)
    np.random.shuffle(coorsy)
    np.random.shuffle(coorsz)

    coors = np.array(list(product(coorsz,coorsy,coorsx))).astype(np.int32)
    coors = coors[0:500,:]
    coors = torch.from_numpy(coors)

    x = scn_input((coors, voxels))
    x = scn_conv1(x)
    print(scn_todense(x).shape)

The output is:
torch.Size([0, 64, 10, 20, 30])

While, I changed "scn.Convolution(dim, 128, 64, (**1, 1, 1**), (1,1,1), bias=False)"  to "scn_conv1 = scn.Convolution(dim, 128, 64, (**3, 1, 1**), (1,1,1), bias=False)"
I got a valid output: 
torch.Size([1, 64, 8, 20, 30])

May I know if I am doing anything wrong? or by definition, 1*1*1 sparse conv is supposed to return an empty tensor?

**Comment by btgraham** [comment]
Hmm, the output shouldn't be empty, but for 1x1x1 convolutions, please replace
`scn.Convolution(dim, 128, 64, (1, 1, 1), (1,1,1), bias=False)`
with
`scn.NetworkInNetwork(128,64, bias=False)`
(Network In Network paper: https://arxiv.org/abs/1312.4400)

scn.Convolution recalculate the sparsity metadata, which is unnecessary for 1x1x1 convolution, while NetworkInNetwork is just a single SGEMM function call.

**Comment by bigsheep2012** [comment]
Thanks for the reply. It works but the essential reason that we use sparse conv is that it has good performance and gives a good speed. I have checked the NIN paper.  Is it actually adding more parameters to the model which may reduce the speed?

**Comment by btgraham** [comment]
As I understand it, 'Network in Network' just means 1x1 convolutions. They were originally used to add depth to fairly shallow ConvNets, but 1x1 convolutions are used for example in ResNet to create skip connections.
