### ISSUE TITLE
Can SparseConvNet run on CPU?

### ISSUE THREAD

**Issue by dongxiao92** [facebookresearch/SparseConvNet#60]
I'm not clear on how SCN proceeds recently.  I remembered the operators of SCN were implemented on GPU. So I'd like to know if SCN can run on a pure CPU environment now.

Thanks

**Comment by btgraham** [comment]
Models by default run on the cpu. They only run on the gpu is you call 'model.cuda'.
See https://github.com/facebookresearch/SparseConvNet/blob/master/examples/hello-world.py for an example.
Ben
