### ISSUE TITLE
build error: AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_2' or Segmengault

### ISSUE THREAD

**Issue by dongxiao92** [facebookresearch/SparseConvNet#61]
Hi, I  try to install SCN. When I follow the installation guide, I encountered the error:
Processing dependencies for sparseconvnet==0.2
Finished processing dependencies for sparseconvnet==0.2
Traceback (most recent call last):
  File "examples/hello-world.py", line 30, in <module>
    input = scn.InputBatch(2, inputSpatialSize)
  File "/home/dongxiao/working/SparseConvNet/sparseconvnet/inputBatch.py", line 19, in __init__
    self.metadata = Metadata(dimension)
  File "/home/dongxiao/working/SparseConvNet/sparseconvnet/metadata.py", line 17, in Metadata
    return getattr(sparseconvnet.SCN, 'Metadata_%d'%dim)()
AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_2'
I find a possible solution in [https://github.com/facebookresearch/SparseConvNet/issues/56](url). But when I tried 'bash develop.sh', I encountered new error:
Processing dependencies for sparseconvnet==0.2
Finished processing dependencies for sparseconvnet==0.2
develop.sh: line 10: 19335 Segmentation fault      (core dumped) python examples/hello-world.py

## Environment
OS:CentOS release 6.6 (Final)
python:Python 3.6.7 :: Anaconda
gcc:gcc (GCC) 4.8.2

**Comment by dongxiao92** [comment]
I've solved this problem. The cause is the compiler gcc4.8.2  is incompatible with that used to compile pytorch. When installing pytorch through conda, the package is compiled by gcc 4.9.2.  The compiler I used is gcc 4.8.2. The difference of compiler results a null pointer being referenced in pybind. After compiling sparseconvnet with gcc 4.9, the segmentfault disappears.

**Comment by ryontang** [comment]
> I've solved this problem. The cause is the compiler gcc4.8.2 is incompatible with that used to compile pytorch. When installing pytorch through conda, the package is compiled by gcc 4.9.2. The compiler I used is gcc 4.8.2. The difference of compiler results a null pointer being referenced in pybind. After compiling sparseconvnet with gcc 4.9, the segmentfault disappears.

hi, thanks for your share for how this problem fixed, i also meet this problem, you said "installing pytorch through conda, the package is compiled by gcc 4.9.2.". I  don't know how do you get the gcc version is 4.9.2 when installing pytorch. In my anaconda env, I input python it shows the gcc(7.2.0), but when I input gcc -V it shows gcc version 5.4.0.

So my question is do I need to unify the gcc version.
In anaconda
![image](https://user-images.githubusercontent.com/39891618/103450056-d638bc00-4ceb-11eb-969c-f6a83bba291b.png)
![image](https://user-images.githubusercontent.com/39891618/103450983-2cf8c280-4cf9-11eb-844c-a6b3e45916fc.png)
