### ISSUE TITLE
Passing metadata through convolution

### ISSUE THREAD

**Issue by dongxiao92** [facebookresearch/SparseConvNet#62]
Hi, I'm learning the implementation of the SCN. But I encounter some problems and hope to get some advice from you.
When I  see the convolution code, I find the metadata of input is passed directly to the output. Both the convolution and submanifold convolution are implemented this way. The code in convolution is shown below:
#### the forward in sparseconvnet/convolution.py

`def forward(self, input):`

        assert input.features.nelement() == 0 or input.features.size(1) == self.nIn

        output = SparseConvNetTensor()

        output.metadata = input.metadata

As I understand, the metadata holds the valid spatial positions and information of which positions are required to compute each valid position in the convolution output. Because convolution can change valid spatial positions, I do not understand why the output can reuse the input metadata. In the submanifold [paper](https://arxiv.org/abs/1706.01307), only the valid submanifold convolution makes the assumption that the valid spatial positions will not change during the convolution. So does the convolution and the submanifold convolution make the same assumption in the code?  Thus, the valid position can be resued until a 'breaking' operation like downsampling. But what if convolution uses stride>1? If I'm wrong, could you please let me know where the metadata is updated?

Another problem is about the rulebook. I think the rulebook depends on the valid positions of the input, the shape of input, and the convolution configuration(filter size, stride, etc). But in the convolution computation, I find the rulebook is indexed without the valid positions. The code is listed below:
#### cpu_Convolution_updateOutput in sparseconvnet/SCN/CPU/Convolution.cpp
`
auto _rules = m.getSubmanifoldRuleBook(inputSize, filterSize, true);
`
#### cpu_SubmanifoldConvolution_updateOutput in sparseconvnet/SCN/CPU/Convolution.cpp
`
auto _rules = m.getRuleBook(inputSize, outputSize, filterSize, filterStride, true);
`
So how can the rule can be determined without knowing the valid positions?

Thanks!

**Comment by btgraham** [comment]
The `metadata' object:
https://github.com/facebookresearch/SparseConvNet/blob/master/sparseconvnet/SCN/Metadata/Metadata.h
stores all the hash tables and rule books for a minibatch, as it passes through the network.
For example:
std::unordered_map<Point<dimension>, Int, IntArrayHash<dimension>> nActive;
stores the number of active sites at a given spatial scale, i.e. nActive[(32,32,32)]=123.
Similarly for rulebooks. This allows the submanifold convolution rulebooks to be re-used by different layers at the same spatial scale.

**Comment by dongxiao92** [comment]
> The `metadata' object:
> https://github.com/facebookresearch/SparseConvNet/blob/master/sparseconvnet/SCN/Metadata/Metadata.h
> stores all the hash tables and rule books for a minibatch, as it passes through the network.
> For example:
> std::unordered_map<Point, Int, IntArrayHash> nActive;
> stores the number of active sites at a given spatial scale, i.e. nActive[(32,32,32)]=123.
> Similarly for rulebooks. This allows the submanifold convolution rulebooks to be re-used by different layers at the same spatial scale.
Thanks for your reply.
So layers with the same scale use the same hash tables of the valid spatial positions. Does this mean we assume the valid positions would not change as long as the spatial scale stays unchanged?
And in the convolution operation, there is a 'stride' parameter. When stride>1, the output spatial size will change. So I think we need to construct the hash table for the output feature. Why the convolution pass the metadata to the output directly in this situation?
