### ISSUE TITLE
Question about calculating FLOPs

### ISSUE THREAD

**Issue by DonDzundza** [facebookresearch/SparseConvNet#65]
I saw in the paper there were graphs plotting 'mean IoU over FLOPs'. I wonder how those numbers of FLOPs were measured or calculated?

**Comment by btgraham** [comment]
It is the average number of multiply-add operations per test case, e.g. 
multiplying an AxB matrix by a BxC matrix is counted as ABC.

See for example
https://github.com/facebookresearch/SparseConvNet/blob/b7e68f6a049f2d27ca86205e522d71b96e74bc1f/sparseconvnet/SCN/CPU/Convolution.cpp#L52-L72
