### ISSUE TITLE
downsample layer use SubmanifoldConvolution?

### ISSUE THREAD

**Issue by mjjdick** [facebookresearch/SparseConvNet#70]
Hi, I found that when there need a downsample the layer will become sparseconv instead of the submanifoldconv for all the nets in networkArchitectures. If use the sparseconv not the submanifoldconv, the value will spread to neighbourhood, and the meaning to submanifold accelerate will be discounted. so , I want to ask why and do we must use sparse conv in the downsample layer?

**Comment by btgraham** [comment]
Submanifold convolutions are like size=3 stride=1 padding=1 convolutions that form the majority of convolutions in a VGG/ResNet/DenseNet type network. They preserve the sparsity pattern, so they cannot be used for downsampling.

When you downsample, with stride=2, space becomes smaller, so it is ok if the sparsity is reduced.

e.g. Think of a diagonal line of length 64 in 64x64 square.
At the input scale, 64 out of 64x64 sites are active.
Downscaling, 32 out of 32x32 sites are active.
Downscaling again, 16 out of 16x16 sites are active.
The percentage of active sites increases, but the number of active sites is  not.
