### ISSUE TITLE
Build a network stacking a mixture of sparse layers and traditional model

### ISSUE THREAD

**Issue by jack8722** [facebookresearch/SparseConvNet#71]
Hello,

thank you so much for your work, it is indeed genius and one of the first of its kind!
 I have a huge input binary images and it is very sparse, I plan to use your work to reduce it using Sparse Convolutions and Max Pooling in pytorch.

Is it possible to build a model directly from torch.nn.Module stacking in a sequential manner Sparse convolutions and, after a SparseToDense layer use only traditional convolutions?

Thanks again for your work!

**Comment by btgraham** [comment]
Yes. For example, if the input is size 10,240, you can have 10 layers of max-pooling (to downscale by a factor or 2**10=1024), followed by SparseToDense to produce output of size 10x10 spatially.
You have to have enough memory to store the output of the SparseToDense layer in memory.

**Comment by jack8722** [comment]
Thank you for your quick response! I'm struggling a bit to do that actually! 
I'm trying to do a task similar to MNIST but with images very very big (20000 like I mentioned previously) so at the beginning of the network I'd like to use your framework but after the SparseToDense layer I would like to use my current NN. Do you happened to have a simple example where you a similar work? I tried to work on the examples in the repository but I was unable to understand how the whole framework works...

**Comment by btgraham** [comment]
What do the images look like? Do you have a sample? What percentage of the pixels are non-zero (i.e. not the background color)?

**Comment by btgraham** [comment]
Do you have an example image? What is the scale of the interesting features? What is the sparsity percentage in the input layer? Are the active locations clustered together?
