### ISSUE TITLE
Assertion error scn.convolution kernel 2 stride 1

### ISSUE THREAD

**Issue by micaeltchapmi** [facebookresearch/SparseConvNet#74]
Hi, I am trying to perform scn.convolution with a stride of 1 and kernel size of 2 but I get an assertion error. I would like to know if that is possible and how it could be implemented.

**Comment by btgraham** [comment]
For a residual connection? I could implement it, but I doubt it would do what you want. Stride=1 kernel size=2 means (in 2D) that you are chucking away 75% of the pixels. In the dense case, that is fine for residual connections as adjacent pixels contain similar information. But in the sparse setting, you may be unlucky and chuck away all the active locations. 

I would recommend downsampling using 
AveragePooling, or MaxPooling, or Convolution 
with size=2 stride=2

Or you can look at the SparseResNet example, which downsamples with size=3 stride=2 
https://github.com/facebookresearch/SparseConvNet/blob/dcd1428dcc769d175734260764eeadf160593335/sparseconvnet/networkArchitectures.py#L140

**Comment by btgraham** [comment]
Oops, misread you question. What is the input size?
Is the assertion this one:
        assert ((output.spatial_size - 1) * self.filter_stride +
                self.filter_size == input.spatial_size).all(), (input.spatial_size,output.spatial_size,self.filter_size,self.filter_stride)
?

**Comment by micaeltchapmi** [comment]
Yes, that is the assertion. The input.spatial_size is 4096

**Comment by btgraham** [comment]
> Yes, that is the assertion. The input.spatial_size is 4096, output.spatial_size is 2048, kernel 2 and stride 1

If the input spatial size is 4096:
scn.Convolution with size=2 stride=1 gives output size 4095
scn.Convolution with size=2 stride=2 gives output of size 2048
scn.SubmanifoldConvolution with size=3 gives output of size 4096 (stride=1, padding=1 is implicit)

**Comment by micaeltchapmi** [comment]
You're right, my mistake. The output size will be 4095 not 2048. I now get it. Thanks!
