### ISSUE TITLE
what's the difference between "deconvolution" and "unpooling"?

### ISSUE THREAD

**Issue by brotherNanNan** [facebookresearch/SparseConvNet#75]
Hi, I find the FCN network adopt "unpooling" for upsample while the Unet use "deconvolution". Can you tell the difference?
And, if the "unpooling" you implemented is the commonly used "Max unpooling" or not? 
thank you.

**Comment by btgraham** [comment]
Unpooling and Deconvolution both reverse a previous downsampling step, restoring the previous sparsity pattern. 

Unpooling copies (additively if receptive fields overlap) values from input to output like (https://pytorch.org/docs/stable/_modules/torch/nn/modules/upsampling.html#Upsample). It is not MaxUnPooling.

Deconvolution has trainable parameters, so it is more like ConvTranspose2d (https://pytorch.org/docs/stable/_modules/torch/nn/modules/conv.html#ConvTranspose2d)
