### ISSUE TITLE
Data processing for scannet

### ISSUE THREAD

**Issue by TonythePlaneswalker** [facebookresearch/SparseConvNet#76]
I am confused by a few data processing and augmentation schemes in `examples/ScanNet/data.py`. 
I would really appreciate it if some explanation could be provided. Specifically,
1. What is [`full_scale`](https://github.com/facebookresearch/SparseConvNet/blob/dcd1428dcc769d175734260764eeadf160593335/examples/ScanNet/data.py#L15)? Is the point cloud cropped using this parameter?
2. How is this [`offset`](https://github.com/facebookresearch/SparseConvNet/blob/dcd1428dcc769d175734260764eeadf160593335/examples/ScanNet/data.py#L68) calculated? It seems that the scene is randomly translated by this parameter.
3. It also seems that noises are added in this [`elastic`](https://github.com/facebookresearch/SparseConvNet/blob/dcd1428dcc769d175734260764eeadf160593335/examples/ScanNet/data.py#L36) function. Are these Gaussian noises on the point locations?

**Comment by btgraham** [comment]
1) 4096x4096x4096 is the receptive field of the sparse ConvNet in voxels. Divide by 'scale' to get the size of the receptive field in metres. All the ScanNet scenes should fit. 
2) Offset just places the scene somewhere randomly in the receptive field.
3) See figure 2 in http://cognitivemedium.com/assets/rmnist/Simard.pdf. A tensor is filled with Gaussian noises, then smoothed to perform elastic distortion.

**Comment by zdw-qingdao** [comment]
@btgraham  I am also confused by the data processing of scannet.
1. m=np.matmul(m,[[math.cos(theta),math.sin(theta),0],[-math.sin(theta),math.cos(theta),0],[0,0,1]])
Why is there an ‘m’？ What's the function of it?

2. elastic(x,gran,mag)
what's the meaning of 'gran' and 'mag' ?
Could you explain these code?
            a=elastic(a,6*scale//50,40*scale/50)
            a=elastic(a,20*scale//50,160*scale/50)

**Comment by btgraham** [comment]
1. m is an affine linear transformation matrix for data augmentation purposes. (rotation, stretch, etc)
2. gran (i.e. granularity) changes the size of the grid used; this affects the scale of the correlation in the elastic distortion noise. mag (i.e. magnitude) increases the size of the distortion.
