### ISSUE TITLE
How fast is training on the scannet benchmark?

### ISSUE THREAD

**Issue by micaeltchapmi** [facebookresearch/SparseConvNet#78]
I am training a large network on the ScanNet dataset with the parameters specified in the Readme.md However, I find the training to be really slow. I am training on 8 v100 GPUs with a batch_size of 32 and a single epoch takes about 35 minutes. I would like to know how long training took to achieve the benchmark? and also, what hardware was used in the training. Thanks!

**Comment by btgraham** [comment]
That seems kind of slow.
What value of `m`, `block_reps` etc are you using?
The training is only set up to use one GPU. Please can you check `htop` and `nvidia-smi` to see how many CPU-cores / GPUs are being used.

**Comment by micaeltchapmi** [comment]
m=32, block_reps=2, residual_blocks=True, scale=50, val_reps=1, batch_size=32. I am running the experiment on the cloud with 8GPUs and 64CPU cores. All CPUs and GPUs are been used when I run the above commands.

**Comment by btgraham** [comment]
Are other jobs running at the same time? I don't see how all the GPUs can be being used otherwise?

**Comment by liarba** [comment]
Hi, I have the same problem. I use the same m, block_reps, scale setting with @micaeltchapmi . But I use just one GPU (Titan X) with batch size 3. I find a single epoch takes about 50 minutes.  I'm wondering how many GPUs you use and how many epochs it takes to get the results on ScanNet benchmark? Thank you very much!

**Comment by micaeltchapmi** [comment]
There are no other jobs running

**Comment by btgraham** [comment]
With one 16GB GPU and settings
```
m = 32
residual_blocks=True
block_reps = 2 
scale=50
val_reps=1
batch_size=8 #Just about fit in memory
```
training starts like:
```
Training examples: 1201
Validation examples: 312
#classifer parameters 30104372
1 Train loss 1.8464586182145883 MegaMulAdd= 51495.849896632804 MegaHidden 81.15866767027477 time= 681.0477819442749 s
1 1 Val MegaMulAdd= 49401.691494666666 MegaHidden 83.65472492307693 time= 138.37022304534912 s
```
i.e. ~11 mins per epoch.

**Comment by btgraham** [comment]
> There are no other jobs running and data loading is very fast so the GPUs are saturated.

Training should use at most one GPU. SparseConvNet simply is not set up to use more than one??

**Comment by liarba** [comment]
> With one 16GB GPU and settings
> 
> ```
> m = 32
> residual_blocks=True
> block_reps = 2 
> scale=50
> val_reps=1
> batch_size=8 #Just about fit in memory
> ```
> training starts like:
> 
> ```
> Training examples: 1201
> Validation examples: 312
> #classifer parameters 30104372
> 1 Train loss 1.8464586182145883 MegaMulAdd= 51495.849896632804 MegaHidden 81.15866767027477 time= 681.0477819442749 s
> 1 1 Val MegaMulAdd= 49401.691494666666 MegaHidden 83.65472492307693 time= 138.37022304534912 s
> ```
> i.e. ~11 mins per epoch.

Thank you, everything seems right except the epoch time. I think it may be caused by the differences between the hardware:(

**Comment by btgraham** [comment]
> > > There are no other jobs running and data loading is very fast so the GPUs are saturated.
> > 
> > 
> > Training should use at most one GPU. SparseConvNet simply is not set up to use more than one??
> 
> So using DataParallel would not work?

No, sorry.

**Comment by micaeltchapmi** [comment]
I have been using Dataparallel to run the experiment and that's how I saw all 8 GPUs been used. can you explain why you say sparseconvnet is not set up for multiple GPUs?

**Comment by btgraham** [comment]
Operations with dense tensors can be split across multiple GPUs automatically. Sparse tensors cannot trivially be split across multiple GPUs. SparseConvNet could use multiple GPUs if the batches were prepared correctly, but this is not implemented.
