### ISSUE TITLE
Any Idea for ScanNet Semantic Instance? (not label)

### ISSUE THREAD

**Issue by NicksonYap** [facebookresearch/SparseConvNet#80]
Hi @btgraham 

Congrats on scoring top in ScanNet 3D Semantic Label!

I've tried the SCN semantic label example so far and it's been smooth sailing and produced great results

I'm trying to implement Semantic Instance using SCN,  but I'm really new to ML
I've read quite a number of papers, namely:
1. 3D-SIS (currently top in Semantic Instance ScanNet benchmark)
2. R-PointNet (https://arxiv.org/abs/1812.03320)

They all seem to use 2D RGB Masks (obtain 2D semantic instances), and projected back onto 3D Points which are then used to generate 3D semantic instances

However they aren't as straight forward / easy as it seems

Do you have any idea how they can be implemented in this repo?

Happy to test out and submit PRs

**Comment by btgraham** [comment]
There are different clustering algorithms that could be applied to the semantic labelled points cloud in 3D (e.g. https://scikit-learn.org/stable/modules/clustering.html) Beyond that, I cannot help.
