### ISSUE TITLE
Prepare data disable 'desk' label for ScanNet 

### ISSUE THREAD

**Issue by liu115** [facebookresearch/SparseConvNet#83]
I want to reproduce the test result of SparseConvNet on [ScanNet benchmark](http://kaldir.vc.in.tum.de/scannet_benchmark/). But line 14-16 in `prepare_data.py` force 'desk' to become 'table'. Why? Wouldn't this cause the model unable to learn and produce the prediction of label 'desk'?

```python
LABEL_ID_TO_CLASS_ID = {
    9: 3 #force 'desk' to be the same class_id as 'table'
}
```

**Comment by btgraham** [comment]
Hmm. I used prepare_data in the form:
https://github.com/facebookresearch/SparseConvNet/blob/dcd1428dcc769d175734260764eeadf160593335/examples/ScanNet/prepare_data.py
