### ISSUE TITLE
Set up error

### ISSUE THREAD

**Issue by RenChangHow** [facebookresearch/SparseConvNet#85]
Hi,

I encountered this problem when trying to run bash develop.sh
The error message is like below:
running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
building 'sparseconvnet.SCN' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/sparseconvnet
creating build/temp.linux-x86_64-3.7/sparseconvnet/SCN
/usr/local/cuda/bin/nvcc -I/mnt/data_j/changhao/anaconda3/envs/pillar_env2/include -I/mnt/data_j/changhao/PointPillar/SparseConvNet/sparseconvnet/SCN/ -I/mnt/data_j/changhao/anaconda3/env
s/pillar_env2/lib/python3.7/site-packages/torch/lib/include -I/mnt/data_j/changhao/anaconda3/envs/pillar_env2/lib/python3.7/site-packages/torch/lib/include/TH -I/mnt/data_j/changhao/anaco
nda3/envs/pillar_env2/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/mnt/data_j/changhao/anaconda3/envs/pillar_env2/include/python3.7m -c sparseconvnet/SCN
/cuda.cu -o build/temp.linux-x86_64-3.7/sparseconvnet/SCN/cuda.o -std=c++11 -Xcompiler -fopenmp -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC'
gcc -pthread -B /mnt/data_j/changhao/anaconda3/envs/pillar_env2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/data_j/changh
ao/anaconda3/envs/pillar_env2/include -I/mnt/data_j/changhao/PointPillar/SparseConvNet/sparseconvnet/SCN/ -I/mnt/data_j/changhao/anaconda3/envs/pillar_env2/lib/python3.7/site-packages/tor
ch/lib/include -I/mnt/data_j/changhao/anaconda3/envs/pillar_env2/lib/python3.7/site-packages/torch/lib/include/TH -I/mnt/data_j/changhao/anaconda3/envs/pillar_env2/lib/python3.7/site-pack
ages/torch/lib/include/THC -I/usr/local/cuda/include -I/mnt/data_j/changhao/anaconda3/envs/pillar_env2/include/python3.7m -c sparseconvnet/SCN/sparseconvnet_cuda.cpp -o build/temp.linux-x
86_64-3.7/sparseconvnet/SCN/sparseconvnet_cuda.o -std=c++11 -fopenmp -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
sparseconvnet/SCN/sparseconvnet_cuda.cpp:14:29: fatal error: torch/extension.h: No such file or directory
 #include <torch/extension.h>
                             ^
compilation terminated.
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "examples/hello-world.py", line 8, in <module>
    import sparseconvnet as scn
ModuleNotFoundError: No module named 'sparseconvnet'

Can anyone help me with this problem?

Thank you.

**Comment by btgraham** [comment]
The compiler is failing to find "torch/extension.h"
Are you using an up to date version of PyTorch, i.e. does 
```
import torch
print(torch.__version__)
```
return 1.0?

**Comment by RenChangHow** [comment]
> The compiler is failing to find "torch/extension.h"
> Are you using an up to date version of PyTorch, i.e. does
> 
> ```
> import torch
> print(torch.__version__)
> ```
> 
> return 1.0?

Thank you! Updating PyTorch version to 1.0 helps.
