### ISSUE TITLE
error: command '/usr/local/cuda:/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by AI-liu** [facebookresearch/SparseConvNet#86]
(pointpillars) cicv@cicv-XPS-8930:~/PointPillars/SparseConvNet$ bash develop.sh running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
building 'sparseconvnet.SCN' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/sparseconvnet
creating build/temp.linux-x86_64-3.7/sparseconvnet/SCN
/usr/local/cuda:/bin/nvcc -I/home/cicv/anaconda3/envs/pointpillars/include -I/home/cicv/PointPillars/SparseConvNet/sparseconvnet/SCN/ -I/home/cicv/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/lib/include -I/home/cicv/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/cicv/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/lib/include/TH -I/home/cicv/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda:/include -I/home/cicv/anaconda3/envs/pointpillars/include/python3.7m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.7/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
unable to execute '/usr/local/cuda:/bin/nvcc': No such file or directory
error: command '/usr/local/cuda:/bin/nvcc' failed with exit status 1
Traceback (most recent call last):
  File "examples/hello-world.py", line 30, in <module>
    input = scn.InputBatch(2, inputSpatialSize)
  File "/home/cicv/PointPillars/SparseConvNet/sparseconvnet/inputBatch.py", line 19, in __init__
    self.metadata = Metadata(dimension)
  File "/home/cicv/PointPillars/SparseConvNet/sparseconvnet/metadata.py", line 17, in Metadata
    return getattr(sparseconvnet.SCN, 'Metadata_%d'%dim)()
AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_2'

**Comment by AI-liu** [comment]
~/.bashrc 
export PATH=$PATH:/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export CUDA_HOME=/usr/local/cuda:$CUDA_HOME

**Comment by AI-liu** [comment]
delete export CUDA_HOME=/usr/local/cuda:$CUDA_HOME
It is OK now.

**Comment by rishabhjoshi** [comment]
Updating cuda to 10.0 and pytorch to 1.4 solved it for me.
