### ISSUE TITLE
questions for setup

### ISSUE THREAD

**Issue by hanxuel** [facebookresearch/SparseConvNet#87]
Hi, I am a student from ETH and I am trying to replicate your work for scannet segmentation. But I meet the problem when try to set up.
I try to train the model on university's GPU cluster, but I can't install anaconda on GPU cluster because my hostname is not in sudoer file. Do you have any idea how to install the dependencies without using sudo-- or conda--?

Best regards

**Comment by btgraham** [comment]
Maybe:
1. Install a recent version of PyTorch.
2. Install https://github.com/sparsehash/sparsehash
3. Run 'python setup.py develop' . You may need to adjust the paths so the compiler can see your sparsehash installation.
