### ISSUE TITLE
error to bash develop.sh

### ISSUE THREAD

**Issue by 58733511** [facebookresearch/SparseConvNet#91]
Hi,
I encountered this problem when trying to run bash develop.sh
The error message is like below:

(pointpillars) leicwan@cmtcvc7u018:~/Downloads/SparseConvNet$ bash develop.sh
running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
building 'sparseconvnet.SCN' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/sparseconvnet
creating build/temp.linux-x86_64-3.7/sparseconvnet/SCN
gcc -pthread -B /lhome/leicwan/anaconda3/envs/pointpillars/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/lhome/leicwan/anaconda3/envs/pointpillars/include -I/lhome/leicwan/Downloads/SparseConvNet/sparseconvnet/SCN/ -I/lhome/leicwan/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/include -I/lhome/leicwan/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/lhome/leicwan/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/include/TH -I/lhome/leicwan/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/include/THC -I/lhome/leicwan/anaconda3/envs/pointpillars/include/python3.7m -c sparseconvnet/SCN/pybind.cpp -o build/temp.linux-x86_64-3.7/sparseconvnet/SCN/pybind.o -std=c++11 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /lhome/leicwan/anaconda3/envs/pointpillars/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/lhome/leicwan/anaconda3/envs/pointpillars/include -I/lhome/leicwan/Downloads/SparseConvNet/sparseconvnet/SCN/ -I/lhome/leicwan/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/include -I/lhome/leicwan/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/lhome/leicwan/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/include/TH -I/lhome/leicwan/anaconda3/envs/pointpillars/lib/python3.7/site-packages/torch/include/THC -I/lhome/leicwan/anaconda3/envs/pointpillars/include/python3.7m -c sparseconvnet/SCN/sparseconvnet_cpu.cpp -o build/temp.linux-x86_64-3.7/sparseconvnet/SCN/sparseconvnet_cpu.o -std=c++11 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
sparseconvnet/SCN/sparseconvnet_cpu.cpp: In function ‘at::Tensor CopyFeaturesHelper_updateOutput(at::Tensor, at::Tensor, at::Tensor)’:
sparseconvnet/SCN/sparseconvnet_cpu.cpp:586:52: error: could not convert ‘cpu_CopyFeaturesHelper_updateOutput<float>(at::Tensor(rules), at::Tensor(context), at::Tensor(Context))’ from ‘void’ to ‘at::Tensor’
   return cpu_CopyFeaturesHelper_updateOutput<float>(rules, context, Context);
                                                    ^
sparseconvnet/SCN/sparseconvnet_cpu.cpp: In function ‘at::Tensor CopyFeaturesHelper_updateGradInput(at::Tensor, at::Tensor, at::Tensor)’:
sparseconvnet/SCN/sparseconvnet_cpu.cpp:591:55: error: could not convert ‘cpu_CopyFeaturesHelper_updateGradInput<float>(at::Tensor(rules), at::Tensor(dcontext), at::Tensor(dContext))’ from ‘void’ to ‘at::Tensor’
   return cpu_CopyFeaturesHelper_updateGradInput<float>(rules, dcontext,
                                                       ^
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "examples/hello-world.py", line 8, in <module>
    import sparseconvnet as scn
ModuleNotFoundError: No module named 'sparseconvnet'

the Version of pytorch is
conda install pytorch-nightly -c pytorch

Thanks for your help!

**Comment by btgraham** [comment]
Thanks for the report. Modification pushed.

**Comment by 58733511** [comment]
hello, have you already solved the Problem?
Thanks from Germany

**Comment by btgraham** [comment]
Please try 'git pull' and reinstalling.
