### ISSUE TITLE
sparseconvnet/SCN/CPU/Convolution.cpp:12:50: error: 

### ISSUE THREAD

**Issue by HTL2018** [facebookresearch/SparseConvNet#93]
when I run "bash develop.sh":This error appeared:  
(I run in ubuntu16.04 CUDA10.0 2080Ti)  

" " "
running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
building 'sparseconvnet.SCN' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/sparseconvnet
creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN
/usr/local/cuda/bin/nvcc -I/home/htl/.conda/envs/py36/include -I/home/htl/second.pytorch-1.0/second/SparseConvNet/sparseconvnet/SCN/ -I/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include -I/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/TH -I/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/htl/.conda/envs/py36/include/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
gcc -pthread -B /home/htl/.conda/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/htl/.conda/envs/py36/include -I/home/htl/second.pytorch-1.0/second/SparseConvNet/sparseconvnet/SCN/ -I/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include -I/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/TH -I/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/htl/.conda/envs/py36/include/python3.6m -c sparseconvnet/SCN/sparseconvnet_cuda.cpp -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/sparseconvnet_cuda.o -std=c++11 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from sparseconvnet/SCN/sparseconvnet_cuda.cpp:29:0:
sparseconvnet/SCN/CPU/Convolution.cpp: In function ‘at::Tensor rule_index_select(at::Tensor, Int, Int*)’:
**sparseconvnet/SCN/CPU/Convolution.cpp:12:50: error: invalid initialization of reference of type ‘const c10::TensorOptions&’ from expression of type ‘at::DeprecatedTypeProperties’
   auto target = at::empty({nRules, n}, src.type());**
                                                  ^
In file included from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/ATen/ATen.h:11:0,
                 from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from sparseconvnet/SCN/sparseconvnet_cuda.cpp:14:
/home/htl/.conda/envs/py36/lib/python3.6/site-packages/torch/include/ATen/Functions.h:3642:22: note: in passing argument 2 of ‘at::Tensor at::empty(c10::IntArrayRef, const c10::TensorOptions&)’
 static inline Tensor empty(IntArrayRef size, const TensorOptions & options) {
                      ^
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "examples/hello-world.py", line 8, in <module>
    import sparseconvnet as scn
ModuleNotFoundError: No module named 'sparseconvnet'
" " "

the problem confused me some days. Look forward for your reply.

**Comment by btgraham** [comment]
The internal PyTorch api had changed. Please 'git pull' and try again.

**Comment by HTL2018** [comment]
Thank you for your reply.
