### ISSUE TITLE
unable to execute ':/usr/local/cuda-8.0/bin/nvcc': No such file or directory

### ISSUE THREAD

**Issue by liqisa** [facebookresearch/SparseConvNet#94]
when i try to install SparseConvNet，By “bash build.sh” 

running install
running bdist_egg
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/denseToSparse.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/permutohedralSubmanifoldConvolution.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/randomizedStrideConvolution.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/sparseConvNetTensor.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/submanifoldConvolution.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/maxPooling.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/networkArchitectures.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/classificationTrainValidate.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/activations.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/identity.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/utils.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/dropout.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/ioLayers.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/batchNormalization.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/metadata.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/deconvolution.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/shapeContext.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/sparsify.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/convolution.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/averagePooling.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/inputBatch.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/networkInNetwork.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/tables.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/randomizedStrideMaxPooling.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/__init__.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/sequential.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/fullConvolution.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/spectral_norm.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/sparseToDense.py -> build/lib.linux-x86_64-3.7/sparseconvnet
copying sparseconvnet/unPooling.py -> build/lib.linux-x86_64-3.7/sparseconvnet
running build_ext
building 'sparseconvnet.SCN' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/sparseconvnet
creating build/temp.linux-x86_64-3.7/sparseconvnet/SCN
:/usr/local/cuda-8.0/bin/nvcc -I/home/deeper/anaconda3/envs/pointpillar/include -I/home/deeper/workspace/SparseConvNet/sparseconvnet/SCN/ -I/home/deeper/anaconda3/envs/pointpillar/lib/python3.7/site-packages/torch/include -I/home/deeper/anaconda3/envs/pointpillar/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/deeper/anaconda3/envs/pointpillar/lib/python3.7/site-packages/torch/include/TH -I/home/deeper/anaconda3/envs/pointpillar/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-8.0/include -I/home/deeper/anaconda3/envs/pointpillar/include/python3.7m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.7/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
unable to execute ':/usr/local/cuda-8.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-8.0/bin/nvcc' failed with exit status 1
Traceback (most recent call last):
  File "examples/hello-world.py", line 10, in <module>
    import sparseconvnet as scn
ModuleNotFoundError: No module named 'sparseconvnet'
-----------------------------------------------------------------------------------------------------------------------
it may concerned about "sudo" i guessed.
so i try 'sudo python setup.py install "
but "sudo python" is usr/bin/python2.7 not the conda python
then i try that "sudo /home/deeper/anaconda3/envs/my_env/python setup.py install "
Another error occur..

 Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import torch, os
  File "/home/deeper/anaconda3/envs/pointpillar/lib/python3.7/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: libnvToolsExt.so.1: cannot open shared object file: No such file or directory
----------------------------------------------------------------------------------------------------------------------
how can I install SparseConvNet correctly?
Thank a lot!

**Comment by btgraham** [comment]
Can you run 'nvcc --version' as a regular user (without sudo)?

**Comment by liqisa** [comment]
> Can you run 'nvcc --version' as a regular user (without sudo)?

of course. 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by PlaneryAlex** [comment]
@liqisa -- we got a similar problem - however we try to test inside the nvidia-cuda docker container, are you running in a docker container as well?

**Comment by liqisa** [comment]
> @liqisa -- we got a similar problem - however we try to test inside the nvidia-cuda docker container, are you running in a docker container as well?

No I didn't use docker.

**Comment by Arctanxy** [comment]
I got the same problem , and my nvcc information is :

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

**Comment by liqisa** [comment]
> I got the same problem , and my nvcc information is :
> 
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2017 NVIDIA Corporation
> Built on Fri_Nov__3_21:07:56_CDT_2017
> Cuda compilation tools, release 9.1, V9.1.85

I had solved this problem. Check your cuda_path in "~/.bashrc"
Maybe caused by the format. 
As the error log shown ":/usr/local/cuda-8.0/bin/nvcc " there is a ":"
Delete this ":"
Good luck.
