### ISSUE TITLE
questions for spatial size

### ISSUE THREAD

**Issue by ThreeBucks** [facebookresearch/SparseConvNet#95]
Hi,
First, thanks for the excellent project. I'm trying to use sparseconv in my 2D semantic segmentation task.But the spatial size in input layer confused me a lot. the size of image is 224*224,batchsize is 4. output size is (2,224,224) that 2 is the number of label.when i use spatialSize=[224,224],mode 3, it occured 'Segment error (core dumped)'. 
Could you help me about how to set spatial size corrently?

**Comment by btgraham** [comment]
Is your input spatially-sparse? InputLayer expects to be given lists of coordinates and corresponding feature vectors. Can you give an example input, please?

**Comment by ThreeBucks** [comment]
yeah, it is spatially-sparse.objects only take about 2% pixels which are curves.it looks like this:
![GT_AIGLE_RN_C18a1](https://user-images.githubusercontent.com/35280961/56729270-67ba0180-6787-11e9-9754-3565203267e4.png)

**Comment by btgraham** [comment]
Is the first picture the input. If so, I would not call it spatially sparse as 99% of the pixels seem to be non zero.

**Comment by ThreeBucks** [comment]
ok, i got it, thanks.
