### ISSUE TITLE
error: google/dense_hash_map: No such file or directory

### ISSUE THREAD

**Issue by lyp0413** [facebookresearch/SparseConvNet#96]
running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
building 'sparseconvnet.SCN' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/sparseconvnet
creating build/temp.linux-x86_64-3.6/sparseconvnet/SCN
/usr/local/cuda/bin/nvcc -I/home/stevencui/anaconda3/include -I/home/stevencui/SparseConvNet/sparseconvnet/SCN/ -I/home/stevencui/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/stevencui/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/stevencui/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/stevencui/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/stevencui/anaconda3/include/python3.6m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.6/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -Xcompiler -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0
In file included from sparseconvnet/SCN/cuda.cu:8:0:
/home/stevencui/SparseConvNet/sparseconvnet/SCN/Metadata/Metadata.h:15:33: fatal 
error: google/dense_hash_map: No such file or directory
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
Traceback (most recent call last):
  File "examples/hello-world.py", line 8, in <module>
    import sparseconvnet as scn
ModuleNotFoundError: No module named 'sparseconvnet'

**Comment by btgraham** [comment]
Have you run EITHER
conda install google-sparsehash -c bioconda   
OR
apt-get install libsparsehash-dev
first?

**Comment by dahyun-kang** [comment]
conda install google-sparsehash -c bioconda didn't work, but apt-get install libsparsehash-dev did work for me. Thank you!

**Comment by TangAL0203** [comment]
apt-get install libsparsehash-dev is good for me, thanks!

**Comment by ytliu74** [comment]
When you use `conda install google-sparsehash -c bioconda`, you need to manually add the path to the header files (`{CONDA}/envs/{ENV_NAME}/include`), to your include path.

**Comment by leo9344** [comment]
> When you use `conda install google-sparsehash -c bioconda`, you need to manually add the path to the header files (`{CONDA}/envs/{ENV_NAME}/include`), to your include path.

I encountered this error when I'm trying to install [torchsparse](https://github.com/mit-han-lab/torchsparse) from source on the machine that I do not have `sudo`.
This `conda install google-sparsehash -c bioconda` and add the path `export PATH=/path/to/anaconda3/envs/yourenv/include:$PATH` is good for me. Much appreciated!
