### ISSUE TITLE
How to get the output of internal feature map

### ISSUE THREAD

**Issue by liu115** [facebookresearch/SparseConvNet#99]
I try to get the encoder output in the encoder-decoder structure. When I pass the encoder output through `scn.OutputLayer` and get the `[N, d]` feature map with original size `N`. 
But since the convolution with strides makes the spatial size smaller, I want to get the points location `[N', 3]` and feature map `[N', d]` that `N'` < `N`. Is this possible?

**Comment by btgraham** [comment]
Each SparseConvNetTensor has a '.features' property and a '.get_spatial_locations()' method. Is that what you want?
